### ISSUE TITLE
how to write custom aggregation query

### ISSUE THREAD

**Issue by vishaltomar76** [babenkoivan/elastic-scout-driver-plus#102]
@babenkoivan 

I want to write a query something like 
curl -X GET "localhost:9200/sports/athlete/_search?size=0&pretty" -H 'Content-Type: application/json' -d'
{
 "aggs" : {
   "athletes" : {
     "filters" : {
       "filters" : {
         "defenders" : { "term" : { "role" : "defender" }},
         "forwards" : { "term" : { "role" : "forward" }}
         }
       },
      "aggs" : {
        "avg_goals" : { "avg" : { "field" : "goals" } }
       }
     }
  }
}

And Expecting below output
...
"aggregations" : {
   "athletes" : {
     "buckets" : {
       "defenders" : {
         "doc_count" : 4,
         "avg_goals" : {
           "value" : 71.25
          }
        },
       "forwards" : {
         "doc_count" : 9,
         "avg_goals" : {
           "value" : 661.0
          }
      }
   }
  }
 }

**Comment by babenkoivan** [comment]
Hi @vishaltomar76, please check the documentation [here](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/available-methods.md#aggregate).
