### ISSUE TITLE
IndexConfigurator and SearchRule migration from scout-elasticsearch-driver

### ISSUE THREAD

**Issue by mvalee** [babenkoivan/elastic-scout-driver-plus#105]
Hi @babenkoivan , love the work you're doing on this project.
I'm migrating my projects from the now-deprecated "scout-elasticsearch-driver" to the newer package(s).

Perhaps I overlooked it, however I can't seem to find instructions for the `IndexConfigurator`'s and `SearchRule`'s I had configured in the old package.
Is this functionality provided in the newer packages as well?

Thanks for your reply!

**Comment by babenkoivan** [comment]
Hey @mvalee, new packages work a bit differently 🙂

You can use [elastic-migrations](https://github.com/babenkoivan/elastic-migrations) to set up an index. This can be considered as the `IndexConfigurator` substitution. 

There are no `SearchRule`s now, but you can use the [Query](https://github.com/babenkoivan/elastic-scout-driver-plus#query) to build a search request.
