### ISSUE TITLE
Setting a bool via value() transforms the type

### ISSUE THREAD

**Issue by renzo-s** [babenkoivan/elastic-scout-driver-plus#107]
Not sure if this is a design decision, but it does not seem logical when doing:

```php
Query::term()->field('boolean_field')->value(true);
```
That it results in an error: `failed to create query: Can't parse boolean value [1], expected [true] or [false]`

Doing (notice the string value 'true'):

```php
Query::term()->field('boolean_field')->value('true');
```
Successfully executes. 

This behaviour has changes since Elastic Search 6.x and only allows real boolean values, as the error indicates.

**Comment by babenkoivan** [comment]
Hey @renzo-s, thank you for submitting a bug!

It should be fixed now in [v3.2.1](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v3.2.1) 🎉
