### ISSUE TITLE
models() and onlyModels() returning Support Collection instead of Eloquent Collection

### ISSUE THREAD

**Issue by iget-master** [babenkoivan/elastic-scout-driver-plus#109]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 8.1.1
| Elasticsearch            | 7.3.0
| Laravel                      | 8.80.0
| Laravel Scout           | 9.4.2
| Elastic Scout Driver | 2.0.0
| Elastic Scout Driver Plus | 3.2.1

**Describe the bug**

This package is using the wrong Collection instance for models. 

**To Reproduce**

Using the `elastic-scout-driver` (not plus), the following behavior happens:

```
SomeModel::search($query)->orderBy('name', 'asc')->get();
// Instance of Illuminate\Database\Eloquent\Collection
SomeModel::search($query)->orderBy('name', 'asc')->paginate(25)->getCollection();
// Instance of Illuminate\Database\Eloquent\Collection
```

but when using `elastic-scout-driver-plus`, the behavior is different:

```
SomeModel::searchQuery($query)->sort('name', 'asc')->execute()->models();
// Instance of Illuminate\Support\Collection
SomeModel::searchQuery($query)->sort('name', 'asc')->paginate(25)->onlyModels()->getCollection();
// Instance of Illuminate\Support\Collection
```

Both collections are compatible, but the Support Collection doesn't allow for example running `$collection->load(['relationship'])`, so I manually need to convert it into a Eloquent Collection.

**Current behavior**
Result collection is an instance of `Illuminate\Support\Collection`

**Expected behavior**
Result collection should be an instance of `Illuminate\Database\Eloquent\Collection`

**Comment by babenkoivan** [comment]
Hey @iget-master, this makes total sense to me. I've just published [v3.2.3](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v3.2.3) with a fix 👍
