### ISSUE TITLE
Combine search() and highlight?

### ISSUE THREAD

**Issue by fernandocoronatomf** [babenkoivan/elastic-scout-driver-plus#11]
Hi @babenkoivan ,

I am using Elastic Cloud Plus driver along with Elastic Cloud driver.
Is it possible to do Model::search() and then do the highlighting()?

I am trying to do a like query, but apparently that only works with Model::search()?

This works as a %like%
`
       Search status to match like %op%  and returns 1

        $results = Model::search('op*')
            ->get();
`
`
       This returns 0

        $results = Model::boolSearch()
            ->filter('term', ['status', 'op*'])
            ->execute();
`
Do I have to do the search() indeed or am I missing something about filter()?
Thanks very much.

**Comment by fernandocoronatomf** [comment]
Sorry, I just worked it out.

**Comment by fernandocoronatomf** [comment]
Hi @babenkoivan 

I know I closed the issue but I have a quick question. 
The above code worked, but what if I need to choose one or more fields using wildcards?
I take that ES does not allow you to do that so what would you recommend?

So my original question comes back to mind, if I do
```
   $results = Model::search('op*')
        ->get();
```

I'll get any field containing op* but then I don't have the highlighting API.
Trying to come up with the best solution here and maybe then I can help you updating the readme if you're fine with it just to add some documentation.

**Comment by babenkoivan** [comment]
Hi @fernandocoronatomf, `elastic-scout-driver` uses [query string](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html) under the hood. You can easily reproduce this query:

```php
$results = Model::search('op*')
    ->get();
```

with `boolSearch`:

```php
$results = Model::boolSearch()
    ->must('query_string', ['query' => 'op*'])
    ->execute();
```

Of course, you can add highlighting in the second query. Does it answer your question?

**Comment by fernandocoronatomf** [comment]
It does. Thanks @babenkoivan 
I have been using all your packages related to ES and learning ES on the go so I appreciate your time to help.

Just another question, do you plan to add a nested() method?
If yes, I can raise a PR if you'd like to...
I was thinking about:

`
        $results = Model::rawSearch()
            ->query([
                'nested' => [
                    'path' => 'messages',
                    'query' => [
                        'bool' => [
                            'must' => [
                                'match' => [
                                    'messages.message' => 'This is the message Activity'
                                ]
                            ]
                        ]
                    ]
                ],
            ])`

To have a method such as:

`
Model::rawSearch()->nested('must', path: 'messages',  field: 'message')
`

**Comment by babenkoivan** [comment]
Hey @fernandocoronatomf, I do not plan to add any methods in `rawSearch`, but I do plan to add new types of search, e.g. `matchSearch`, `termSearch`, etc. `nestedSearch` might be of them, but I can't say when it will be released.

**Comment by fernandocoronatomf** [comment]
Cool. Awesome. Let me know if you'd like any help for that so I can raise a PR.
Also, I am trying to add inner_hits on a nested array and it is throwing me an error.
Should that be working or you're not supporting that yet?

I am trying to do this:

`GET my-index-000001/_search
{
  "query": {
    "nested": {
      "path": "user",
      "query": {
        "bool": {
          "must": [
            { "match": { "user.first": "Alice" }},
            { "match": { "user.last":  "White" }} 
          ]
        }
      },
      "inner_hits": { 
        "highlight": {
          "fields": {
            "user.first": {}
          }
        }
      }
    }
  }
}`

**Comment by babenkoivan** [comment]
Hey @fernandocoronatomf, I've finally added [nested search](https://github.com/babenkoivan/elastic-scout-driver-plus#nested-search) in [v1.8.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.8.0) 🎉

**Comment by fernandocoronatomf** [comment]
Awesome. Thanks mate
