### ISSUE TITLE
aggregate return empty

### ISSUE THREAD

**Issue by sbh96** [babenkoivan/elastic-scout-driver-plus#111]
when i create aggregate with aggregate method i get empty data 

 `$query = Query::matchAll();
$product_query = Products::searchQuery($query)
            ->size(0)
            ->aggregate('stock_statuses', [
                "terms" => [
                    "field" => "status"
                ]])->execute();
         return $product_query->aggregations();`

returns :
`
"stock_statuses": {}
`

but when i replace aggregations with raw method like this aggregations object return successfully:

`
   $query = Query::matchAll();
        $product_query = Products::searchQuery($query)
            ->size(0)
            ->aggregate('stock_statuses', [
                "terms" => [
                    "field" => "status"
                ]])->execute();
         return $product_query->raw();
`

returns to me:

`
 {
        "took": 0,
        "timed_out": false,
        "_shards": {
            "total": 1,
            "successful": 1,
            "skipped": 0,
            "failed": 0
        },
        "hits": {
            "total": {
                "value": 10000,
                "relation": "gte"
            },
            "max_score": null,
            "hits": []
        },
        "aggregations": {
            "stock_statuses": {
                "doc_count_error_upper_bound": 0,
                "sum_other_doc_count": 0,
                "buckets": [
                    {
                        "key": "active",
                        "doc_count": 128168
                    }
                ]
            }
        }
    }
`

**Comment by babenkoivan** [comment]
Hey @sbh96, I can't reproduce the issue. I've tried the parser with your raw response and I was able to get buckets and other fields like this:

```php
// array of fields
$searchResponse->aggregations()->get('stock_statuses')->raw();
// collection of buckets
$searchResponse->aggregations()->get('stock_statuses')->buckets();
```

Please make sure you use the latest package version.
