### ISSUE TITLE
Feature Request - Search_after integration

### ISSUE THREAD

**Issue by gtapps** [babenkoivan/elastic-scout-driver-plus#114]
Hello,

Currently there is no support for elastic search_after parameter:
https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html#search-after

Which is a problem, as we get a error when retrieving paginated results when the index.max_result_window is passed.

Gabriel

**Comment by babenkoivan** [comment]
Hi @gtapps, this feature requires some interface changes and therefore can't be included in the current package version. I've noted it for the future version 4, but can't give you an approx. release window yet.

**Comment by babenkoivan** [comment]
Hi @gtapps, the feature is now available in [v4.0.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v4.0.0) 🎉 You can see the usage example [here](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/available-methods.md#searchafter). Points in time are also supported, you can read about how to create one [here](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/available-methods.md#pointintime). Please note, that the new version only supports Elasticsearch 8.
