### ISSUE TITLE
Methode size() not working at elasticsearch Version 7.10.2

### ISSUE THREAD

**Issue by Jules-Verne** [babenkoivan/elastic-scout-driver-plus#118]
I just want to use to limit the result to a fixed number of hits, but the Method size() isn't working and will be irgnored.

**Comment by babenkoivan** [comment]
Hi @Jules-Verne, why are you sure that it isn't working? You can see what is actually sent to Elasticsearch with the following code:

```php
dd(Model::searchQuery($query)->size(10)->buildSearchRequest()->toArray());
```

**Comment by Jules-Verne** [comment]
Hi

it was my mistake.
I have tried to use the size method together with the pagination mode.
Stupid idea ;-)

Thanks
