### ISSUE TITLE
Join in custom query builders

### ISSUE THREAD

**Issue by sunnythewebdeveloper** [babenkoivan/elastic-scout-driver-plus#12]
Hi,

How can I add multiple index search support using "->join()" in custom query builders making use of QueryBuilderInterface ?

In below mentioned case the same query will run on "Book" as specified for "Author" in FormQueryBuilder.

`Author::searchForm()->name('wolf')->join(Book::class)->execute()->models()`

Are there better ways that allow providing custom query for joining index "Book" ?

**Comment by babenkoivan** [comment]
Hi @sunnythewebdeveloper, I'm not sure if I understand the question correctly. Do you want to change `searchForm` behaviour depending on the joined models? It's currently not possible as `QueryBuilder` is isolated and doesn't know anything about the joined models.

The main purpose of `QueryBuilder` is to construct a query, if you search in multiple indices, then this query must match documents in every index. If `name` field in your example belongs to `Author` and `Book`, then I don't see any problem to use it like you mentioned:

```php
Author::searchForm()->name('wolf')->join(Book::class)->execute()->models()
```

If it belongs only to `Author` and you want also to search by `title` when `Book` is joined you can do:

```php
Author::searchForm()->name('wolf')->join(Book::class)->title('foo')->execute()->models()
```

Of course, having `title` method doesn't make sense if you search in `Author` only:

```php
Author::searchForm()->title('foo')->execute()->models()
```

It will not break anything, it just feels wrong. To solve this issue you can create another query builder, which would extend your `FormQueryBuilder`:

```php
class FormWithBooksQueryBuilder extends FormQueryBuilder
{
    public function title(string $title): self
    {
    }
}
```

and then add a method in your model:

```php
class Author 
{
    public function searchFormWithBooks(): SearchRequestBuilder
    { 
        return (new SearchRequestBuilder(new static(), new FormWithBooksQueryBuilder()))->join(Book::class);
    }
}
```

As you can see, `Book` is predefined in the builder returned by `searchFormWithBooks`. Now you can search only authors:

 ```php
Author::searchForm()->name('wolf')->execute();
```

or authors and books:

 ```php
Author::searchFormWithBooks()->name('wolf')->title('foo')->execute();
```

I hope I've answered your question 🙂

**Comment by sunnythewebdeveloper** [comment]
@babenkoivan Thanks a lot for helping out :+1:
