### ISSUE TITLE
mustRaw, shouldRaw, etc is overwrited by posterior query builders

### ISSUE THREAD

**Issue by Surt** [babenkoivan/elastic-scout-driver-plus#125]
Hi!

On this example:

``` 
 Query::bool()
                    ->mustRaw(....)
                    ->must(.....)
``` 

when printing the resulted query it seems that the "must" query does delete the entire "mustRaw" query (although it was setted (printing the resulted between calls)

It does not happend when I use only ```Query::must``` for the two. (Right now I'm having a big query that is easier to set as a Raw one)

**Comment by babenkoivan** [comment]
Hey @Surt, this shouldn't happen. I even have a test case for this scenario:

```php
$expected = [
    'bool' => [
        'must' => [
            ['term' => ['year' => 2019]],
            ['term' => ['year' => ['value' => 2020]]],
        ],
    ],
];

$actual = Query::bool()
    ->mustRaw(['term' => ['year' => 2019]])
    ->must(
        Query::term()
            ->field('year')
            ->value('2020')
    )
    ->buildQuery();

$this->assertEquals($expected, $actual);
```

Can you please share your code, which doesn't work?
