### ISSUE TITLE
Support case_insensitive field parameter

### ISSUE THREAD

**Issue by paranarimasu** [babenkoivan/elastic-scout-driver-plus#128]
The `case_insensitive` field parameter was recently added in version 7.10.0 for some term-level queries. I have a use case where there is some discrepancy in behavior between filtering in Eloquent and Elasticsearch that would be remedied by enabling this parameter, but there does not appear to be a trait in this package yet.

Supported Term-Level Queries:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-prefix-query.html#prefix-query-field-params
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-regexp-query.html#regexp-query-field-params
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-term-query.html#term-field-params
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html#wildcard-query-field-params

**Comment by babenkoivan** [comment]
Hi @paranarimasu, thank you for reaching out. I've added it to my to-do list.

**Comment by babenkoivan** [comment]
Hey again 🙂 I've just noticed your PR and released a new [v3.5.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v3.5.0) version that includes your changes. Thank you for your contribution!
