### ISSUE TITLE
Support for Laravel Pagination

### ISSUE THREAD

**Issue by Bernardino18** [babenkoivan/elastic-scout-driver-plus#13]
Hi,
I´m trying to get results from a query and i would like models() function support the paginate() function from laravel.

Similiar like this below

Model::boolSearch()->must(
                'query_string', ['query' => '*'.request()->value.'*']
)->execute()->models()->paginate(20);

**Comment by Bernardino18** [comment]
Already found a solution using LengthAwarePaginator (Illuminate\Pagination\LengthAwarePaginator) of Laravel

$total = Model::boolSearch()->must(
                'query_string', ['query' => '*'.request()->value.'*']
            )->execute()->total();

            $items =  Model::boolSearch()->must(
                'query_string', ['query' => '*'.request()->value.'*']
            )->from($offsetIndex)->size($perPage)->execute()->models();
            
            $paginator = new LengthAwarePaginator($items, $total, $perPage, $currentPage);

            return response()->json($paginator);

**Comment by babenkoivan** [comment]
Hey @Bernardino18, I probably need to add `paginate` method in the search request builder to be able to do something as follows:

```php
Model::boolSearch()->must(
    'query_string', ['query' => ''.request()->value.'']
)->paginate();
```

I've added it in my todo list to check if it makes sense and possible to implement.

**Comment by Surt** [comment]
Hello, I'm in the process on refactoring all my old scout-elasticsearch-driver code to the new "ecosystem"
This one is really clean about atomizing requests etc when complex queries are used so I am very pleased at the moment.
My main concern is about pagination too. That was the entire reason to change to this library. (on the other one I had no clue of writing pagination on top of a raw search)

Again, as always, thanks @babenkoivan for your efforts!

**Comment by babenkoivan** [comment]
Just a short update on the topic: I'm currently working on a big update, which brings a bunch of often used full text query builders and after that I'm planning to work on the pagination. I'd say it will be ready in 2 weeks or so 🙂

**Comment by Surt** [comment]
> Just a short update on the topic: I'm currently working on a big update, which brings a bunch of often used full text query builders and after that I'm planning to work on the pagination. I'd say it will be ready in 2 weeks or so 🙂

Great! I'm in the process of a 'funtion_score' builder, I will post it here when done.

**Comment by Juanperezc** [comment]
> Just a short update on the topic: I'm currently working on a big update, which brings a bunch of often used full text query builders and after that I'm planning to work on the pagination. I'd say it will be ready in 2 weeks or so


great, we will be waiting for this update, I also need the pager hehe.

**Comment by babenkoivan** [comment]
The pagination is now available, please update to [v1.10.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.10.0) and read the docs [here](https://github.com/babenkoivan/elastic-scout-driver-plus#search-result) 🎉

**Comment by Surt** [comment]
I can't get the `models()` when traversing the matches returned by the `paginate` method. It always return null for those matches.

**Comment by babenkoivan** [comment]
@Surt can't reproduce the issue, can you open a `bug` issue with code examples and your setup configuration?

**Comment by filippesic** [comment]
Hello everyone,

I've been trying to get pagination to work for hours without success. My issue is pretty similar if not identical to Surt's.

`File::matchPhraseSearch()->field('ocr_text')->query(\request('query'))->execute()->models()` this works with all the accessors from `File` model, but has no pagination

`File::matchPhraseSearch()->field('ocr_text')->query(\request('query'))->paginate(20)` this doesn't have any accessors whatsoever and `models()` cannot be called anywhere when `pagination()` is used, only works with `execute()`

Apologies for just jumping in. I just thought I could be helpful.

**Comment by babenkoivan** [comment]
@filippesic, when you do `$paginator = File::matchPhraseSearch()->field('ocr_text')->query(\request('query'))->paginate(20)` you get back a `LengthAwarePaginator` instance, not a `SearchResult` as in case with `execute`. `LengthAwarePaginator` doesn't have the same interface (methods), but you can traverse matches as follows:

```php
foreach ($paginator as $match) {
    $model = $match->model();
}
```

or you can get all the matches via `LengthAwarePaginator::items()`:

```php
$matches = $paginator->items();
```

if you are interested in models only, something like this should work:

```php
$models = collect($paginator->items())->map->model();
```

**Comment by filippesic** [comment]
@babenkoivan Thank you so much! This works for me `@for(collect($paginator->items())->map->model())`, tho that might not be as clean. I did notice the difference in returned data with `paginate()` and `execute()` and I saw through `dd()` there's a `LazyModelFactory` in there, tho I couldn't figure out how to access that data. Now everything works, except that my searched `query` from the input field is missing on other pages, but I guess I messed up something else.

**Comment by babenkoivan** [comment]
@filippesic maybe I need to add couple more examples in the README or make a custom paginator, which would allow to access `models()`, `documents()`, etc. the same way as `SearchResult` does.. 

Anyway, if you need to loop through the models a cleaner way would be:

```
@foreach ($paginator as $match)
     {{ $match->model()->id }}
@endforeach
```
As for the query string, I do not append any query parameters in the pagination links. In contrast to the default scout driver, plus version allows you to build very complex search requests, which rely on multiple fields. It's up to developers to define what goes in the pagination. In your case you can do the following:

```php
$paginator = File::matchPhraseSearch()->field('ocr_text')->query(\request('query'))->paginate(20);
$paginator->appends('query', request('query'));
```

**Comment by filippesic** [comment]
@babenkoivan No no no sir, I'm still pretty new in programming. You already helped a lot, no need to waste your time any more. No need to change or add anything, it's me who is inexperienced, that's it. :)
I solved `query` problem with `..paginate(20)->withPath('/search?query=' . \request('query')`, but  `appends` is, of course,  how it should be done.
