### ISSUE TITLE
Is there a way to customize how my indexes are imported?

### ISSUE THREAD

**Issue by souljacker** [babenkoivan/elastic-scout-driver-plus#130]
Or when I want to specify it should I create the index using github.com/babenkoivan/elastic-migrations first?

**Comment by marcelopm** [comment]
Yup, you have to use that package or create them manually. Otherwise, a mapping will be automatically created in ES based on the model's provided data for indexing.

**Comment by souljacker** [comment]
Awesome.

It works great.


Thanks for those

Em qua., 20 de jul. de 2022 20:13, Marcelo Moises ***@***.***>
escreveu:

**Comment by babenkoivan** [comment]
Closing as the issue seems to be resolved
