### ISSUE TITLE
How to write more_like_this

### ISSUE THREAD

**Issue by muzidudu** [babenkoivan/elastic-scout-driver-plus#133]
How do you implement this code
`GET /_search
{
  "query": {
    "more_like_this" : {
      "fields" : ["title", "description"],
      "like" : "Once upon a time",
      "min_term_freq" : 1,
      "max_query_terms" : 12
    }
  }
}`

**Comment by babenkoivan** [comment]
Hey @muzidudu, there is currently no builder for `more_like_this` query, but you can use a raw query:

```php
$query = [
    'more_like_this' => [
        'fields' => ['title', 'description'],
        'like' => 'Once upon a time',
        'min_term_freq' => 1,
        'max_query_terms' => 12
    ]
];

$searchResult = Book::searchQuery($query)->execute();
```

**Comment by muzidudu** [comment]
> 

thx for reply !  
I know how to do it.
