### ISSUE TITLE
Inner hits as models

### ISSUE THREAD

**Issue by souljacker** [babenkoivan/elastic-scout-driver-plus#134]
Is there right now a way to directly fetch inner hits as models?

I have a ProductVariant model which has a product_id and a type_id. Those are note enforced for uniqueness in the DB. 

I want to fetch all Variants, but don't have two variants with the same product_id and type_id.

So I did a:

```
   $products = ProductVariant::searchQuery($query)->collapseRaw(
            ['field' => 'product_id',
                'inner_hits' => [
                    'name' => 'by_color',
                    'collapse' => [
                        'field'=> 'color_id',

                    ],
                ],
            ]
        )->sort('product_id', 'asc')->paginate(50);
```

And that works the same as the Kibana query.

The thing is I end up with a list of models collapsed only by product_id.

To get to the inner hits, I can do 

```
  foreach ($products as $product) {
            foreach ($product->innerHits()['by_color'] as $hit) {
                dd($hit);
            }
}
```

But that dd is a ElasticAdapter\Search\Hit class, which has no built in way of converting back to an Eloquent method. Even if that method existed, I'd be hammering my DB twice (once in the original request, which returns the Models by default, and then once more for each inner hit.

Is there a built in better way of doing this?

**Comment by babenkoivan** [comment]
Hey @souljacker, I've just published a new version [v4.1.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v4.1.0), which adds `model` method support for inner hits:

```php
$innerHitModels = $product->innerHits()['by_color']->map->model();
```

It should only make one request to the database. Please reopen the issue if you face any troubles.
