### ISSUE TITLE
Get start_offset and end_offset from highlights

### ISSUE THREAD

**Issue by dade1987** [babenkoivan/elastic-scout-driver-plus#138]
Good evening,

how can i get start_offset, end_offset and position from highlights, with elastic-scout-driver-plus?

Elastic docs says:

`After doc1 is found as a hit for this query, this hit will be passed to the unified highlighter for highlighting the field content of the document. Since the field content was not indexed either with offsets or term vectors, its raw field value will be analyzed, and in-memory index will be built from the terms that match the query:

{"token":"onli","start_offset":12,"end_offset":16,"position":3},
{"token":"fox","start_offset":19,"end_offset":22,"position":5},
{"token":"fox","start_offset":53,"end_offset":58,"position":11},
{"token":"onli","start_offset":117,"end_offset":121,"position":24},`

Docs link: https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html#highlighting

Thank you,
Davide Cavallini

**Comment by babenkoivan** [comment]
Hi Davide,
ES returns only snippets, I don't think you can retrieve this kind of information.
