### ISSUE TITLE
Does this library allow you to build chains of requests?

### ISSUE THREAD

**Issue by dunakov** [babenkoivan/elastic-scout-driver-plus#140]
In other topics i found this 
`
$config = Query::bool()
    ->must(
        Query::multiMatch()
            ->fields (['type', 'label', 'description', 'canonical', 'property', 'building', 'location',])
            ->query ('*'.$request->get ('q').'*')
    )
    ->filter( // you can also use should instead
        Query::term() // you can use match instead
            ->field('property_id')
            ->query('12345')
    );
`

But this is not very convenient. Especially when your request is formed at different points in the project.

When I use it like this
`$paginator = Model::searchQuery()
            ->sort('id', 'desc')
            ->query(Query::wildcard()->field('field1')->value(1))
            ->query(Query::wildcard()->field('field2')->value(2))
            ->paginate(30)`

Requests replace each other. But this is how it is in the code and it turns out that the last query will replace all the previous ones. But as I understand it, this library does not allow you to expand Query from different places in the project.

**Comment by babenkoivan** [comment]
Hi @dunakov, you can always add a query in the service container and access it in different places of the code:

```php
// in the provider
$this->app->singleton(‘my_query’, fn() => Query::wildcard());

// e.g. in a controller
$query = app(‘my_query’);
```
