### ISSUE TITLE
Incorrect total number when using pagination

### ISSUE THREAD

**Issue by skyroses** [babenkoivan/elastic-scout-driver-plus#142]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 8.1.12
| Elasticsearch            | 8.5.0
| Laravel                      | 9.3.12
| Laravel Scout           | 9.4.12
| Elastic Scout Driver | 3.0.1
| Elastic Scout Driver Plus | 4.1.0

**Describe the bug**
I've got 5 items in elasticsearch index, in the name of which, there is "pencil"(red pencil, green pencil, yellow and etc.). I search the "pencil" and then I use the `refineModels` method and add an additional `where` condition to the query builder request, which only 2 out of 5 items correspond to. Just example:

```php
Pencil::searchQuery(
    Query::match()->field('name')
    ->operator('OR')
    ->fuzziness('AUTO')
    ->query('pencil')
)
    ->refineModels(fn ($query) => $query->where('active', true))
    ->paginate(10)
    ->onlyModels()
    ->total();
```

the `items` method return 2 items - it's ok... The problem is that the pagination `total` will return in this case the number from the result from elasticsearch - 5, not 2.

**Current behavior**
5

**Expected behavior**
2

**Comment by babenkoivan** [comment]
Hey @skyroses, Laravel Scout works in the following way:
1. It finds records in a search engine and calculates the total number of results
2. It queries the database to make Eloquent models

`refineModels` is applied on the second step, when the total is already calculated. I would not recommend using this method with pagination. You can add `active` in the index and add a filter to get the correct results.
