### ISSUE TITLE
401 unauthorized issue

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/elastic-scout-driver-plus#143]
Hi,
I just updated to 8.4 and when I try to run php artisan elastic:migrate:refresh I get the error 
`401 Unauthorized: {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/users]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/users]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}},"status":401}`

I can add xpack.security.enabled: false to my yml file but I was wondering if there was a way to keep the security? Sorry if you explain this somewhere that I missed.

**Comment by babenkoivan** [comment]
Hey @chrisgrim, I think you either need to provide credentials or disable `xpack.security` to connect to ElasticSearch.

**Comment by babenkoivan** [comment]
It should be possible, please check this comment https://github.com/babenkoivan/elastic-scout-driver/issues/48#issuecomment-1243038876 for more details. 
You can also pass it as a part of the hostname, i.e. `username:password@localhost:9200`.

**Comment by chrisgrim** [comment]
amazing! Thanks so much for the response and such a great plugin!!
