### ISSUE TITLE
Support for PHP 8.1

### ISSUE THREAD

**Issue by Thavarajan** [babenkoivan/elastic-scout-driver-plus#146]
Got an error when try to do the basic match query

Call to undefined method Elastic\ScoutDriverPlus\Builders\MatchQueryBuilder::value()

**Comment by babenkoivan** [comment]
Hey @Thavarajan, PHP 8.1 is supported. Can you please provide more details: the version of elastic-scout-driver-plus you use and the call stack (trace)?

**Comment by leeovery** [comment]
Im running this on php8.2 with no issues. Just FYI :)
