### ISSUE TITLE
How to reproduce this perfectly valid Elastic query using the package's methods

### ISSUE THREAD

**Issue by ftrudeau-pelcro** [babenkoivan/elastic-scout-driver-plus#148]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.4
| Elasticsearch            | OpenSearch 2.3 (AWS)
| Laravel                      | 8.83.25
| Laravel Scout           | 9.8.1
| Elastic Scout Driver | 2.0.0

**Describe the bug**

Not a bug, rather a question.
How to reproduce this perfectly valid Elastic query with the methods provided by the package?

```
GET _search
{
  "query": {
    "nested": {
      "path": "metadata",
      "query": {
        "bool": {
          "must": [
            { "match_phrase_prefix": { "metadata.key": "the key name" }},
            { "match_phrase_prefix": { "metadata.value": "the key value" }}
          ]
        }
      }
    }
  }
}
```

Defining the raw query like this:

```php
$query = [
    'nested' => [
        'path' => 'metadata',
        'query' => [
            'bool' => [
                'must' => [
                    'match_phrase_prefix' => [
                        'metadata.key' => 'the key name',
                        'metadata.value' => 'the key value',
                    ]
                ]
            ]
        ]
    ]
];
```
... fails with this error:

` {"error":{"root_cause":[{"type":"parsing_exception","reason":"[match_phrase_prefix] query doesn't support multiple fields, found [metadata.key] and [metadata.value]","line":1,"col":128}],"type":"x_content_parse_exception","reason":"[1:128] [bool] failed to parse field [must]","caused_by":{"type":"parsing_exception","reason":"[match_phrase_pre
fix] query doesn't support multiple fields, found [metadata.key] and [metadata.value]","line":1,"col":128}},"status":400}`

And using the package `Query::nested` method like this returns results, event though the Elastic query already mentioned above does not, which is the actual expected behavior:

```php
$query = Query::nested()
    ->path('metadata')
    ->query(Query::matchPhrasePrefix()->field('metadata.key')->query('the key name'))
    ->query(Query::matchPhrasePrefix()->field('metadata.value')->query('the key value'))
;
```

**Comment by babenkoivan** [comment]
Hi @ftrudeau-pelcro, I think your raw query doesn't match the elastic query, it should be something like the following:

```php
$query = [
    'nested' => [
        'path' => 'metadata',
        'query' => [
            'bool' => [
                'must' => [
                    [
                        'match_phrase_prefix' => [
                            'metadata.key' => 'the key name'
                        ],
                    ],
                    [
                        'match_phrase_prefix' => [
                            'metadata.value' => 'the key value'
                        ]
                    ]
                ]
            ]
        ]
    ]
];
```

The same can be achieved with the query helper:

```php
 $query = Query::nested()
    ->path('metadata')
    ->query(
        Query::bool() 
            ->must(Query::matchPhrasePrefix()->field('metadata.key')->query('the key name'))
            ->must(Query::matchPhrasePrefix()->field('metadata.value')->query('the key value'))
    ) ;
```

I did not test it, but this is how I'd construct the query you mentioned above. I hope this helps :)
