### ISSUE TITLE
support for add extra SearchParameters

### ISSUE THREAD

**Issue by chris-lee-lb** [babenkoivan/elastic-scout-driver-plus#150]
Currently I want to enable `request_cache` for my search query without luck. 
(`request_cache` can be added at first level of `$searchParameters` when call `\Elastic\Elasticsearch\Client::search($searchParameters)`)

So may we have new function to make add extra search parameters ? Thanks.

**Comment by babenkoivan** [comment]
Hey @chris-lee-lb, I've added it in [v4.5.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v4.5.0) 🎉 You can find the documentation [here](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/available-methods.md#requestcache).
