### ISSUE TITLE
How to filter an empty string

### ISSUE THREAD

**Issue by loveshiun** [babenkoivan/elastic-scout-driver-plus#153]
| Software                   | Version
| --------------------| ---------------
| PHP                           | x.y.z
| Elasticsearch            | x.y.z
| Laravel                      | x.y.z
| Laravel Scout           | x.y.z
| Elastic Scout Driver | x.y.z

**Describe the bug**

I tried to use the following query:

```
$query->mustNot(Query::term()->field("my_keyword")->value(""));

```

and it throws an error

```
Elastic\ScoutDriverPlus\Exceptions\QueryBuilderValidationException: All required fields have to be specified: field, value in /var/www/html/vendor/babenkoivan/elastic-scout-driver-plus/src/QueryParameters/Validators/AllOfValidator.php:22
Stack trace:
#0 /var/www/html/vendor/babenkoivan/elastic-scout-driver-plus/src/Builders/AbstractParameterizedQueryBuilder.php(21): Elastic\ScoutDriverPlus\QueryParameters\Validators\AllOfValidator->validate(Object(Elastic\ScoutDriverPlus\QueryParameters\ParameterCollection))
#1 /var/www/html/vendor/babenkoivan/elastic-scout-driver-plus/src/Factories/ParameterFactory.php(18): Elastic\ScoutDriverPlus\Builders\AbstractParameterizedQueryBuilder->buildQuery()
#2 /var/www/html/vendor/babenkoivan/elastic-scout-driver-plus/src/Builders/BoolQueryBuilder.php(59): Elastic\ScoutDriverPlus\Factories\ParameterFactory::makeQuery(Object(Elastic\ScoutDriverPlus\Builders\TermQueryBuilder))

```

when it tried to validate the parameters

src/QueryParameters/Validators/AllOfValidator.php

```
public function validate(ParameterCollection $parameters): void
{
    $isInvalid = $parameters->only($this->required)->excludeEmpty()->count() !== count($this->required);

    if ($isInvalid) {
        throw new QueryBuilderValidationException(
            'All required fields have to be specified: ' .
            implode(', ', $this->required)
        );
    }
}
```

src/QueryParameters/ParameterCollection.php

```
public function excludeEmpty(): self
{
    $items = $this->items->filter(
        static fn ($value) => isset($value) && $value !== '' && $value !== []
    )->all();

    return new self($items);
}
```

Is it possible to have the above mentioned query?

```
$query->mustNot(Query::term()->field("my_keyword")->value(""));

```

**To Reproduce**

```
$query->mustNot(Query::term()->field("my_keyword")->value(""));

```

**Current behavior**

Elastic\ScoutDriverPlus\Exceptions\QueryBuilderValidationException: All required fields have to be specified: field, value in /var/www/html/vendor/babenkoivan/elastic-scout-driver-plus/src/QueryParameters/Validators/AllOfValidator.php:22

**Expected behavior**

An empty string is allowed.

```
{
  "query": {
    "bool": {
      "must_not": [
        {
          "term": {
            "my_keyword": {
              "value": ""
            }
          }
        }
      ]
    }
  }
}

```

**Comment by babenkoivan** [comment]
Hey @loveshiun, thank you for reporting this and providing a detailed analysis! I don't see a reason why we should not allow empty string values for search parameters. I've just released [v4.5.1](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v4.5.1) that fixes the issue 🙂
