### ISSUE TITLE
How to update index on create, update & delete

### ISSUE THREAD

**Issue by KimpShreyan** [babenkoivan/elastic-scout-driver-plus#157]
Not updating - how to update index on create, update & delete with nested items, like an observer am I missing something how to setup the observer rest all working

**Comment by babenkoivan** [comment]
Hi @KimpShreyan, an index should be automatically updated when you save, update, or delete a model. If this is not happening, I recommend you check whether [queues are enabled](https://laravel.com/docs/10.x/scout#queueing) in the scout config and whether consumers are running. 

To add any additional information to the stored document apart from the model attributes, you need to override [`toSearchableArray` method](https://laravel.com/docs/10.x/scout#configuring-searchable-data) in your model.
