### ISSUE TITLE
models() with highlights data

### ISSUE THREAD

**Issue by Surt** [babenkoivan/elastic-scout-driver-plus#16]
Hello,

It's possible to return the models on a `searchResult` with a new added property "highlights"? does it make sense on the library?
I can always add a method to instantiate the models and add the hightlights but... I think it would be great to have it on the library.

`function models(metadata = false)` for future needs?

**Comment by Surt** [comment]
This is what I'm doing now. it does execute the models with 1 query though, wich is great.

```php 
        //  been marks a SearchResult instance
        $marks = $marks->map(function ($mark) {
            $mark_model = $mark->model();

            if ($mark_model && $mark->highlight()) {
                $descriptions = $mark->highlight()->getSnippets('description');
                $mark_model->description = implode(' ', $descriptions);
            };

            return $mark_model;
        })->values()->filter();

        $marks = new Illuminate\Database\Eloquent\Collection($marks);
```

**Comment by babenkoivan** [comment]
I don't think it make sense, because highlights don't belong to the model. You replace model's description field with the highlighted snippets, but you probably do that to display your model nicely. `models` shouldn't modify the actual model data.

**Comment by Surt** [comment]
Yes, I agree with you about model. But let me insist a little
since the model defines a trait searchable and custom search it does not affect the model per se.
On Algolia you can see https://www.algolia.com/doc/framework-integration/laravel/searching/server-side-search/?language=php#results-metadata that scoutMetadata already do that. 

Since the model is defined to use scout there is no model modification if a new property (wich is already present for that purpouse) is filled with scout data.

Right now, the use of `scoutMetadata` on a `searchResult` model seems to be wrong (it generates a exception). Please @babenkoivan give it another oportunity.

**Comment by babenkoivan** [comment]
@Surt, the only purpose of `scoutMetadata` intended by Scout is to add additional information (such as `__soft_deleted` flag) in the index. If you add something in this array and then call `Model::searchable()`, then all these new fields will be indexed as well. I'm not sure how scout-extended handles this, but I don't want to deal with such side effects. Moreover, I don't like this approach anyways, you have clean separation between model and ES metadata in matches:

```php
$searchResult = Model::rawSearch()
    // ...
    ->execute();

$match = $searchResult->matches()->first();

$model = $match->model();
$highlight = $match->highlight();
``` 

Sorry, but I'm not convinced, that I need to duplicated the data (which is already accessible) to another field. It looks like a workaround and does not bring any value.

**Comment by Surt** [comment]
Ok. Anyway did you check the Algolia link? They already implement this. 
In any case your "matches" approach seems good.

Thanks again!
