### ISSUE TITLE
searchableWith Aggregation features

### ISSUE THREAD

**Issue by ybert** [babenkoivan/elastic-scout-driver-plus#160]
For example, I would like to eager load Stores and their associate Product counts.
I have 2 models : Store and Product
One store has many products.

I would like to have a product count in each store to be able to quickly retrieve  store with more than 5 products for example.
It could be great to have the same features than loadCount(), loadSum() etc.... 
We could have searchableWithCount(), searchableWithSum(), etc...

Actually I have to eager load all products of each stores and it is too heavy to load all these objects.

**Comment by babenkoivan** [comment]
Hi @ybert, I think what you are trying to achieve is already possible. I see two options:

1. Use an anonymous function to aggregate results:
```php
// your Store model 

public function searchableWith()
{
    return ['products' => fn($q) => $q->selectRaw('store_id, count(*) as cnt')->groupBy('store_id')];
}

public function toSearchableArray()
{
    $searchable = parent::toSearchableArray();
    $searchable['products_count'] = $this->products->first()->cnt ?? 0;
    return $searchable;
}
```

2. [Decorate](https://laravel.com/docs/10.x/container#extending-bindings) `DocumentFactory`:

```php
class MyDocumentFactory extends DocumentFactory
{
    public function __construct(private DocumentFactory $documentFactory)
    {
    }

    public function makeFromModels(BaseCollection $models): BaseCollection
    {
        if ($loadCount = $models->first()->searchableCount ?? null) {
            $models = new EloquentCollection($models);
            $models->loadCount($loadCount);
        }

        return $this->documentFactory->makeFromModels($models);
    }
}
```

And add a property in your model:
```php
// your Store model 

public $searchableCount = ['products'];
```

I'd prefer to avoid adding more helpers similar to `searchableWith` in the code base. It already covers many scenarios that users might face. For more complicated cases, I'd encourage you to extend or decorate `DocumentFactory`.

**Comment by ybert** [comment]
Thank you @babenkoivan 

Awesome tip for the DocumentFactory. I will try it for further needs.
For the moment I managed it by saving and updating  the count in the SQL table.
This way the performance still good.
