### ISSUE TITLE
mustRaw, shouldRaw, etc is overwriting previous query conditions

### ISSUE THREAD

**Issue by rohitjalmi90** [babenkoivan/elastic-scout-driver-plus#162]
Hello @babenkoivan,

Thank you for awesome package :)

This is regarding previous issue mentioned here : https://github.com/babenkoivan/elastic-scout-driver-plus/issues/125

I was able to reproduce this using following testcases.
Note : All function ie mustRaw, sortRaw ignore the condition prior to using those function.
Testcases you provided are working as expected since mustRaw is before must

Testcase
```
$expected = [
            'bool' => [
                'must' => [
                    ['term' => ['year' => 2019]],
                    ['term' => ['year' => ['value' => 2020]]],
                ],
            ],
        ];
        
$actual = Query::bool()
    ->must(
        Query::term()
            ->field('year')
            ->value('2020')
    )
    ->mustRaw(['term' => ['year' => 2019]])
    ->buildQuery();
$this->assertEquals($expected, $actual);
```

Output : Failed

Query formed : 
{"bool":{"must":{"term":{"year":2019}},"filter":[{"term":{"__soft_deleted":0}}]}}  

Package version : 
```
"babenkoivan/elastic-migrations": "^3.0",
"babenkoivan/elastic-scout-driver-plus": "^4.0",

"name": "babenkoivan/elastic-scout-driver-plus",
 "version": "v4.7.0",

"name": "babenkoivan/elastic-migrations",
 "version": "v3.4.0",
```

**Comment by babenkoivan** [comment]
Hi, @rohitjalmi90, the idea of `mustRaw` and similar functions is to allow you to provide the entire `must` clause in a single call, it completely replaces the "must" clause of the query. When you invoke `mustRaw` you tell the builder to replace "must" with the provided queries, when you call `must` you tell it to add a query to the "must" clause. This is why you can call `mustRaw` and then `must`, but not vice versa. 

 If you want to add just one raw query to the list, you can change your code to:

```php
$actual = Query::bool()
    ->must(
        Query::term()
            ->field('year')
            ->value('2020')
    )
    ->must(['term' => ['year' => 2019]])
    ->buildQuery();
```

Note that `must` also accept an array as input. 

Hope this helps :)

**Comment by babenkoivan** [comment]
I've updated the [documentation](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/compound-queries.md#-must) to make it more clear.
