### ISSUE TITLE
Retrieve Raw Elasticsearch Data

### ISSUE THREAD

**Issue by miyake-123** [babenkoivan/elastic-scout-driver-plus#164]
Hi!
I have problem getting the data.
 the available methods such as:
searchQuery($query)->execute()->hint();
searchQuery($query)->execute()->models();
searchQuery($query)->execute()->documents();

Do not provide a way to retrieve the raw data array as it appears in the content when calling searchQuery($query)->execute()->documents();.
It could be great to have the same features than execute()->documents():
  public function toArray(): array
    {
        return  $this->content;
    }
instead of
 public function toArray(): array
    {
        return [
            'id' => $this->id,
            'content' => $this->content,
        ];
    }

**Comment by babenkoivan** [comment]
Hi @miyake-123, do I understand correctly that you want to retrieve only the content of all documents? You can do it as follows: `searchQuery($query)->execute()->documents()->map->content()`.
