### ISSUE TITLE
Support `geoshape` functionality

### ISSUE THREAD

**Issue by johnbacon** [babenkoivan/elastic-scout-driver-plus#165]
Great package!

One of the major things holding us back from using it exclusively is the ability to utilize [Elasticsearch's geoshape field type](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html).

As a listing-based site with custom "travel" settings, this would be used to show listings that appeared within a user's custom-set bounding boxes and/or travel polygons.

**Comment by babenkoivan** [comment]
Hey @johnbacon, geo shape type is already supported in [the mapping](https://github.com/babenkoivan/elastic-adapter/blob/f2bd15d9d57d8631cf8f86539d815e749109d499/src/Indices/Mapping.php#L26) alongside with other geo types. I've added a [geo shape query](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/geo-queries.md#geo-shape) builder in [v4.8.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v4.8.0), which I hope is enough to build your custom search engine.

**Comment by johnbacon** [comment]
Thank you for the clarification and the great support generally. We appreciate your project!
