### ISSUE TITLE
(Related to issue #132) Synchronous driver operation in tests seeming to be a difficulty

### ISSUE THREAD

**Issue by lukemorcom** [babenkoivan/elastic-scout-driver-plus#166]
Hi,

Just piggybacking off of the only issue that is close to what we are experiencing.

We are using a single node cluster in docker for unit testing. We found that the elastic driver was behaving asynchronously, even when `config('scout.queue')` was set to false.

Consequently we were needing to add a lot of `sleep()` calls across unit tests to ensure the indexes were up to date before making new queries and performing assertions etc.

I stumbled across issue #132 and am so glad I found it. I have only tested removing `sleep()` calls from one of our test classes so far but it appears to be working.

To the point - I'm currently writing a series of action classes to add/remove from an array field for a document, to save pulling the entire model into memory with a `searchable()` call. Rough example:

```        $client = app(ClientBuilderInterface::class)->default();

        $client->update([
            'index' => 'users',
            'id' => $followerId,
            'body' => [
                'script' => [
                    'source' => '
                        ctx._source.followings_ids.remove(
                            ctx._source.followings_ids.indexOf(params.to_unfollow_id)
                        );
                        ctx._source.followings.removeIf(f -> f.id == params.to_unfollow_id);
                    ',
                    'params' => [
                        'to_unfollow_id' => $idToUnfollow,
                    ],
                ],
            ],
        ]);
```

And it seems that using the client this way is still doing things a little bit async, because if I add some `sleep()` back in to the test testing this specific action class, it all passes again.

Hopefully this is coherent enough as I am still in the process of figuring it out, but I will also have a look in the source and see why this might be - but in the meantime I would appreciate if you can let me know if you know any reason why the `elastic.scout_driver.refresh_documents` config being `true` would not be fully respected when interfacing with ES like this?

Thanks!

**Comment by babenkoivan** [comment]
Hi @lukemorcom, `elastic.scout_driver.refresh_documents` is only respected by the `elastic-scout-driver-plus`. Internally, the driver reads the config value and passes it to the client's methods such as `bulk`, `delete`, etc. If you use the client to update an index, you can simply pass this parameter yourself:

```php
$client->update([
    'refresh' => 'true',
    'index' => 'users',
    'id' => $followerId,
    'body' => [
        // ...
    ],
]);
```

I hope this helps 🙂
