### ISSUE TITLE
AbstractParameterizedQueryBuilder add method for get count parameters

### ISSUE THREAD

**Issue by GoldenTypeAV** [babenkoivan/elastic-scout-driver-plus#167]
Hello. I had a problem building a query. I would like to know if it is possible to add a method to the AbstractParameterizedQueryBuilder class to get the number of parameters. Usage example:
```php
<?php

$query = Query::bool();

/* Too many blocks */
if($condition)
  $query = $query->must(Query::exists()...);

if($condition)
  $query = $query->must(Query::exists()...);

if($condition)
      $query = $query->withTrashed();

Model::searchQuery($query->count() ? $query : null)->paginate(25);
```
Or maybe there is some solution?
Thank you in advance

**Comment by GoldenTypeAV** [comment]
At the moment I achieved the result in the following way:

**Comment by babenkoivan** [comment]
Hi @GoldenTypeAV, I believe such a method would have a very limited usage and therefore won't be added to the package. I think you can do something like the following:

```php
$query = Query::bool();
$cnt = 0;

/* Too many blocks */
if ($condition) {
  $query = $query->must(Query::exists()...);
  $cnt++;
}

Model::searchQuery($cnt > 0 ? $query : null)->paginate(25);
```

**Comment by GoldenTypeAV** [comment]
Hi, @babenkoivan, In any case, this will not allow me to specify the withTrashed parameter with an empty number of conditions

**Comment by babenkoivan** [comment]
Hi @GoldenTypeAV,  if you have zero conditions, but want to use a bool query with trashed, you can always do something like:

```php
if ($noConditions) {
    $query->must(Query::matchAll());
}

Model::searchQuery($query->withTrashed())->paginate(25);
```

**Comment by GoldenTypeAV** [comment]
@babenkoivan thanks you
