### ISSUE TITLE
RemoveFromSearch job is dispatched when shouldBeSearchable is set to false

### ISSUE THREAD

**Issue by jacksnchz** [babenkoivan/elastic-scout-driver-plus#168]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 8.2
| Elasticsearch            | 8.6.0
| Laravel                      | 11.33.2
| Laravel Scout           | 10.11.7
| Elastic Scout Driver | 4.0.0
| Elastic Scout Driver Plus | 5.0.0

**Describe the bug**
`Elastic\ScoutDriverPlus\Jobs\RemoveFromSearch` job is dispatched but really the model has `shouldBeSearchable` defined returning false.

**To Reproduce**
```
$media = Media::find(117);
$media->save();
```

**Current behavior**
My model Media is retrieved from database and saved, when I access to my horizon panel, no `MakeSearchable` job is dispatched (correct) but every time I save the model, a new `RemoveFromSearch` job appears.

**Expected behavior**
No dispatching `RemoveFromSearch`

Thank you and congrats for the package.

**Comment by babenkoivan** [comment]
Hey @jacksnchz, the driver doesn't change the standard Laravel Scout behavior, which is defined in the `ModelObserver`:

```php
public function saved($model)
{
    if (static::syncingDisabledFor($model)) {
        return;
    }

    if (! $this->forceSaving && ! $model->searchIndexShouldBeUpdated()) {
        return;
    }

    if (! $model->shouldBeSearchable()) {
        if ($model->wasSearchableBeforeUpdate()) {
            $model->unsearchable();
        }

        return;
    }

    $model->searchable();
}
```

As you can see above, the model will be removed from the index if `shouldBeSearchable` returns `false`. You can set `searchIndexShouldBeUpdated` to return `false` to prevent updates/removals. 

Hope this helps 🙂

**Comment by jacksnchz** [comment]
OMG, i reviewed the Observer and didn't see the logical negation, what a noobie!

Thank u!
