### ISSUE TITLE
Scout driver?

### ISSUE THREAD

**Issue by WimWidgets** [babenkoivan/elastic-scout-driver-plus#19]
How do you use this package as an actual Scout driver? All the features and examples are using a custom builder system that seem to have no relation to Laravel Scout, but acts to replace it (and it's builder). I'm very confused.

**Comment by babenkoivan** [comment]
Hi @WimWidgets, this package is an extension for [elastic-scout-driver](https://github.com/babenkoivan/elastic-scout-driver), you need to install both as described [here](https://github.com/babenkoivan/elastic-scout-driver#installation) and [here](https://github.com/babenkoivan/elastic-scout-driver-plus#installation).
