### ISSUE TITLE
[Documenation] Boost method on multi match search?

### ISSUE THREAD

**Issue by Jonathanm10** [babenkoivan/elastic-scout-driver-plus#20]
Hello,

First, thanks a lot for your packages. We've already have a production project that is using it and now we're looking for implementing it in a new one.

I've seen you made several updates and I'm not sure about one of them. Regarding the `multiMatchSearch` method, you show in the doc that we can add the `boost` method to it. But looking at the `boost` method, it seems to only accept a float, thus not making sense here since we'll usually end up with multiple fields.

In this example, we don't really know on what field it will be added.

```
Book::multiMatchSearch()->fields(['name', 'title'])->boost(3)
```

Shouldn't be something like the following?

```
Book::multiMatchSearch()->fields(['name', 'title'])->boost('name', 3)
```

So is the doc right or am I mistaken something here?

Thanks in advance for your help.

**Comment by babenkoivan** [comment]
Hey @Jonathanm10, to boost specific fields you need to use the caret notation as described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#field-boost):

```php
Book::multiMatchSearch()->fields(['name^3', 'title']);
```

Also, according to the [official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html) the `boost` parameter is supported and therefore it can be used to boost all the fields at once.

**Comment by Jonathanm10** [comment]
@babenkoivan Learning everyday :) 

I ended up boosting fields as you suggested and it works perfectly.

Thanks again for those amazing ES libs and for your time. 
There are so helpful and really well made.
