### ISSUE TITLE
Error with The engine should be an EngineDecorator that has the method

### ISSUE THREAD

**Issue by Gricey404** [babenkoivan/elastic-scout-driver-plus#22]
The engine should be an EngineDecorator that has the method, but the package's service provider isn't executing so it's never properly decorated. Instead he ends up using the main engine class that doesn't have the method.

**Comment by babenkoivan** [comment]
Hi @Gricey404, the package utilizes the [package discovery feature](https://laravel.com/docs/8.x/packages#package-discovery), the service provider has to be picked up by the framework and executed. Please, check if you use the [supported Laravel version](https://github.com/babenkoivan/elastic-scout-driver-plus#compatibility).
