### ISSUE TITLE
" You cannot serialize or unserialize PDO instances "

### ISSUE THREAD

**Issue by gtapps** [babenkoivan/elastic-scout-driver-plus#24]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.4
| Elasticsearch            | x.y.z
| Laravel                      | 6.2
| Laravel Scout           | 7.2
| Elastic Scout Driver | 1.11.0

**Describe the bug**
With the latest commit, it killed most of my sites that are using this package: 
Error is:  You cannot serialize or unserialize PDO instances 
Triggered by     61
    vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php
    PDO
    :295

**To Reproduce**
Update to latest version and use redis to cache the results.

**Current behavior**
When caching the collection retrieved from elastic, it kills the site.

**Expected behavior**
Error should not happen just like before this latest commit.

**Comment by babenkoivan** [comment]
Hi @gtapps , thanks for reporting. Can you provide me the code example you are using to cache the results?

**Comment by babenkoivan** [comment]
Hey @gtapps, I've just released [v1.11.1](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.11.1) with a fix. The issue should be resolved now. Would be nice if you could verify that.

**Comment by gtapps** [comment]
Hello!
Yes it seems to have been fixed. I'll do a few more tests and will close this later today.

Thank you!
G
