### ISSUE TITLE
Whats up with not updating "scout-elasticsearch-driver"?

### ISSUE THREAD

**Issue by rayventerprise** [babenkoivan/elastic-scout-driver-plus#25]
Sorry in advance for posting this here, but it appears the author is only looking in this package and not "scout-elasticsearch-driver" Do you have any plans to keep it maintained as it has over 17 pull requests, 100 issues and appears to be much more used than this package. Would be a huge help to me if you could merge the "custom payload" pull request at the very least so I can add "body.track_total_hits"

Thank you.

**Comment by babenkoivan** [comment]
Hey @rayventerprise, `elastic-scout-driver` and `elastic-scout-driver-plus` are the replacement for `scout-elasticsearch-driver`. The reason I've created the new packages and not the version 5 of `scout-elasticsearch-driver` is that the core logic has changed and I wanted to split functionality in multiple packages.

I was hoping, that the contributors would keep the old project alive, but it looks like it's not maintained at all. Unfortunately, I don't have time for it neither and I believe, that with ES 8 release `scout-elasticsearch-driver` will stop working.

My suggestion is migrate to the new packages 🙂

PS: closing as not related
