### ISSUE TITLE
function_score wrapper

### ISSUE THREAD

**Issue by epicsagas** [babenkoivan/elastic-scout-driver-plus#26]
I am trying to sort by random with `function_score.random_score`, could I wrap with `function_score` in each query statement?

```
GET goods
{
    "query": {
        "function_score": {
            "query": {
                "bool": {
                    "filter": [
                        {"query_string": {
                            "query": "*Ironman*"
                        }}
                    ]
                }
            },
            "random_score": {}
        }
    }
}
```

**Comment by babenkoivan** [comment]
Hi @epicsagas, I'm not sure if I understood your question, but you can do any custom query using [raw search](https://github.com/babenkoivan/elastic-scout-driver-plus#raw-search).

**Comment by epicsagas** [comment]
@babenkoivan Thank you for your answer! It was the `php` issue with empty array. This is solved with `new stdClass()`.
