### ISSUE TITLE
Combine multiple searchs builders

### ISSUE THREAD

**Issue by Surt** [babenkoivan/elastic-scout-driver-plus#27]
Hi, 

how can I combine multiple search builders? I'm triying to perform a search with a bool query wich includes a nested search. It seems that only `rawSearch` will perform this task?

Maybe I can also merge multiple searchbuilders payloads but it dosn't seems pretty.

**Comment by babenkoivan** [comment]
Hi @Surt, there are several options:

1. Use `boolSearch`:

```php
$result = Model::boolSearch()->must('nested', [
    'path' => '...',
    'query' => [...]
]);
```

2. Use `rawSearch` as you've already mentioned

3. Use `NestedQueryBuilder`:

```php
$nestedQuery = (new NestedQueryBuilder())
    ->path('...')
    ->query([...]);

$result = Model::boolSearch()->mustRaw($nestedQuery->buildQuery());
```

I haven't tried the last one, but I guess it should work. It's not documented, because there will be a better way to do that in the future 🙂

**Comment by Surt** [comment]
> 2. Use `NestedQueryBuilder`:
> 
> ```
> $nestedQuery = (new NestedQueryBuilder())
>     ->path('...')
>     ->query([...]);
> 
> $result = Model::boolSearch()->mustRaw($nestedQuery->buildQuery());
> ```

That's brilliant :) thx!
