### ISSUE TITLE
elastic-adapter dependency

### ISSUE THREAD

**Issue by kukukk** [babenkoivan/elastic-scout-driver-plus#28]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.4.3
| Elasticsearch            | 7.9.1
| Laravel                      | 6.18.37
| Laravel Scout           | 8.3.1
| Elastic Scout Driver | 1.2.0

**Describe the bug**
The elastic-adapter dependency for elastic-scout-driver and elastic-scout-driver-plus are different.

**To Reproduce**
I installed elastic-scout-driver when the latest version of elastic-adapter was 1.7.0.
Now, I need additional functionalities, but I can't install elastic-scout-driver-plus because the elastic-adapter dependency can't be satisfied.

**Current behavior**
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install babenkoivan/elastic-scout-driver-plus v1.11.1
    - Conclusion: remove babenkoivan/elastic-adapter v1.7.0
    - Installation request for babenkoivan/elastic-scout-driver-plus ^1.11 -> satisfiable by babenkoivan/elastic-scout-driver-plus[v1.11.0, v1.11.1].
    - Conclusion: don't install babenkoivan/elastic-adapter v1.7.0
    - babenkoivan/elastic-scout-driver-plus v1.11.0 requires babenkoivan/elastic-adapter ^1.7.1 -> satisfiable by babenkoivan/elastic-adapter[v1.7.1, v1.7.2].
    - Can only install one of: babenkoivan/elastic-adapter[v1.7.1, v1.7.0].
    - Can only install one of: babenkoivan/elastic-adapter[v1.7.2, v1.7.0].
    - Installation request for babenkoivan/elastic-adapter (locked at v1.7.0) -> satisfiable by babenkoivan/elastic-adapter[v1.7.0].
```

**Expected behavior**
Install elastic-scout-driver-plus package.

**Comment by babenkoivan** [comment]
Hi @kukukk, please make sure, that `babenkoivan/elastic-adapter` is not locked in your `composer.json`. If so, please remove it and run `composer update babenkoivan/elastic-adapter` and then `composer require babenkoivan/elastic-scout-driver-plus`.

It's fine, that the versions differ in two packages unless there is a conflict. Currently there is no conflict as `elastic-scout-driver` requires `^1.0` (which is `>=1.0, <=2.0`) and `elastic-scout-driver-plus` requires `^1.7.1` (which is `>=1.7.1, <=2.0`).

**Comment by kukukk** [comment]
The `elastic-adapter` is not locked in `composer.json`, so with your 2 commands I was able to install `elastic-scout-driver-plus`.
Thanks!

**Comment by babenkoivan** [comment]
ok, good. Probably I need to update README with an instruction to update `elastic-scout-driver` before installing the plus version.
