### ISSUE TITLE
Is it possible to use when() for searches?

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/elastic-scout-driver-plus#33]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.4.7
| Elasticsearch            | 7.3.2
| Laravel                      | 8.15.0
| Laravel Scout           | 8.4.0
| Elastic Scout Driver | 1.2.0

Hi @babenkoivan 
I would love to do a when() statement (or something similar) with my searches like so:
```
$searchResult = Event::boolSearch()
            ->when($request->price[0], function($query) use ($request) {
                $query->must('range', ['priceranges.price' => [ 'gte' => $request->price[0],'lte' => $request->price[1]]]);
            })
            ->when($request->category, function($query) use ($request) {
                $query->filter('terms', ['category_id' => $request->category]);
            })
            ->paginate(12);
```
However this is giving me the error 
```
Call to undefined method ElasticScoutDriverPlus\Builders\SearchRequestBuilder::when()",…}
```
Is there a way to check if for a submitted variable before searching?

**Comment by babenkoivan** [comment]
@chrisgrim `when` is currently not supported, I've noted it as a feature request. You can use `if` statement for now:

```php
$searchRequest = Event::boolSearch();

if ($request->price[0]) {
    $searchRequest->must('range', ['priceranges.price' => [ 'gte' => $request->price[0],'lte' => $request->price[1]]]);
}

$searchResult = $searchRequest->paginate(12);
```

**Comment by chrisgrim** [comment]
This solution worked perfectly! Thank you so much @babenkoivan. 

Should I close this or leave it open for feature request?

**Comment by babenkoivan** [comment]
Hey @chrisgrim, [when method](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/generic-methods.md#when) has been added in [v1.14.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.14.0) 🎉

**Comment by chrisgrim** [comment]
Wooooo!!! Thanks @babenkoivan !!🎉🎉
