### ISSUE TITLE
How to customize the sorting?

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/elastic-scout-driver-plus#34]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.4.7
| Elasticsearch            | 7.3.2
| Laravel                      | 8.15.0
| Laravel Scout           | 8.4.0
| Elastic Scout Driver | 1.2.0

Hi,
Just checking if there is a way to do more custom sorting? I have the search
```
$searchResult = Event::boolSearch()
->filter('terms', ['category_id' => $request->category])
->should('term', ['showtype' => 'a'])
->should('range', ['shows.date' => [ 'gte' => $request->dates[0],'lte' => $request->dates[1]]])
->minimumShouldMatch(1)
->sort('published_at', 'desc')
->paginate(12);
```
When I do a search for a certain date I get 3 results back, two of them with dates and one that is at anytime. Because of the sort('published_at', 'desc') it shows the events in the order 
```
1. Event- with date
2. Event- anytime
3. Event- with date
```
I believe this is the published at order. However I would prefer that if there were dates it would change the sorting order to 
```
1. Event- with date
3. Event- with date
2. Event- anytime
```
And the events with dates are in published at desc order and the anytime are in published at desc order.
Is this possible?

Thanks so much!!

**Comment by babenkoivan** [comment]
There are 2 methods in your disposal:
* `sort($field, $direction)`
* `sortRaw($parameters)`

The last one is more flexible, so maybe it's something you are looking for. It's not quite clear what is `anytime` (string or missing field), but it's better if you check [ES docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html), there are many useful options, that might help you to configure your sorting.

I'm closing this one as it's not package related, but rather ES related question.
