### ISSUE TITLE
Search returns null because database update but not search update

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/elastic-scout-driver-plus#35]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.4.7
| Elasticsearch            | 7.3.2
| Laravel                      | 8.15.0
| Laravel Scout           | 8.4.0
| Elastic Scout Driver | 1.2.0

**Describe the bug**

I think? the indicies is not updating quickly enough. It sends back data but the model is empty because the data is gone from the database already.

**Current behavior**
After deleting an organizer I then try to pass back all the organizers to the blade file.
```
 public function destroy(Organizer $organizer)
    {
            foreach ($organizer->events as $event) { $event->delete(); }
            
            $organizer->delete();

            return Organizer::matchAllSearch()->load(['user'])->paginate(30);
    }
``` 
The problem is the database will delete the organizer, but when I return the organizers using a matchAllSearch it returns the 30 objects with an empty first object model. The first object has a document id, email and name of the organization I just deleted. However, the model itself is null. Then If I then reload the page and run Organizer::matchAllSearch()->load(['user'])->paginate(30); It will load correctly with the organization completely gone even in the paginated data.

**Expected behavior**
I would expect the matchAllSearch to return the 30 items after the indices has been updated fully.

**Comment by babenkoivan** [comment]
@chrisgrim by default ElasticSearch doesn't index (remove) data right away, so it's possible that you get documents without related models in the search results. You can change this behaviour by setting `ELASTIC_SCOUT_DRIVER_REFRESH_DOCUMENTS ` constant to `true`.

**Comment by chrisgrim** [comment]
Oh nice! I will give this a shot. I also realized I wasn't using async oh my vue method so it wasn't waiting for the return before reloading the page. Thanks for your help again!

**Comment by marcelopm** [comment]
@babenkoivan thanks for pointing that out. We are migrating from the old driver to new ecosystem, it took me a while to find this information. I've searched the new repos docs, but couldn't find it. Might be helpful to state it somewhere in the docs. Cheers
