### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by sicaboy** [babenkoivan/elastic-scout-driver-plus#36]

**Comment by RolandVerner** [comment]
I just saw that I use version 1.0.0 because I have PHP 8 and all features not working.

**Comment by babenkoivan** [comment]
PHP 8 support will be added most likely until the end of this month

**Comment by RolandVerner** [comment]
> PHP 8 support will be added most likely until the end of this month
Nice!
Thanks for the packages!

**Comment by babenkoivan** [comment]
Hi, there 👋🏻 

I've just released a new PHP 8 compatible version [v2.0.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v2.0.0) 🎉  Unfortunately, it was not possible to add PHP 8 support without breaking backward compatibility, so please update your `composer.json` accordingly. The main changes, which require you to make some code adjustments are:

* `CustomSearch` trait was renamed to `QueryDsl`
* `Match` class was renamed to `QueryMatch`

Please, let me know if you face any troubles upgrading to the new version 🙂
