### ISSUE TITLE
Option to have paginate behave similar to Laravel's

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/elastic-scout-driver-plus#37]
Currently if I paginate() I get a list of data objects with
```
document: {id: "22", content: {…}}
highlight: null
index_name: "organizers"
model: {id: 22, user_id: 47, name: "Electric Goldfish", website: null, email: null, …}
score: 1
```
If I paginate with laravel my data just has a list of objects themselves. This is causing me an issue as my entire app is set to look for the object list in data whereas when I use your paginate list the object is in data->model.

Its not that big of a change, but it involves me changing a ton of content through out my site.

**Comment by chrisgrim** [comment]
I figured out a quick workaround that suits my needs. In the /src/Match.php file I changed the toArray()
```
public function toArray()
    {
        $model = $this->model();
        $document = $this->document();
        $highlight = $this->highlight();

        // returns just the model instead of the array
        return $model;

        // return [
        //     'model' => isset($model) ? $model->toArray() : null,
        //     'index_name' => $this->indexName(),
        //     'document' => $document->toArray(),
        //     'highlight' => isset($highlight) ? $highlight->getRaw() : null,
        //     'score' => $this->score(),
        // ];
    }
```

**Comment by babenkoivan** [comment]
Hey @chrisgrim, you shouldn't change the package source code as it might be reverted during the deployment or any other package update. This feature has been already requested and it's in my list.

For now, you can transform the paginate output to include only models:

```php
$paginator = $search->paginate();

$content = tap($paginator->toArray(), function (array &$content) {
    // include only models in the response
    $content['data'] = Arr::pluck($content['data'], 'model');
});

$response = response($content);
```

Hope it helps 🙂

**Comment by Surt** [comment]
I like the `match` pagination. 
Expecially if @babenkoivan is planing to add the elastic "hits" inside each `match`.
On aggregations, custom results, inner-hits, and other kind of searchs the "match" with `hits` will save my day. I care about the models, of course, but I care about the "hits results" I did specify on the searchs.

so, please do not change the pagination to return only plain models instead of matchs.

**Comment by Surt** [comment]
What about a custom pagination collection (extending the laravel one) with a `models` method that taps it inside another paginator collection?

**Comment by chrisgrim** [comment]
Ahh perfect @babenkoivan 
Thanks so much!!

And @Surt I wasn't suggesting we get rid of the pagination array as it is now, just offer a way to have it behave like default Laravels. Eventually I will go through my whole project and update it so it can use the new pagination array but that will be a sometime in the future project.
Thanks again!
