### ISSUE TITLE
help to implement multi-filter search

### ISSUE THREAD

**Issue by mohammadjavadz** [babenkoivan/elastic-scout-driver-plus#39]
Hi
Thanks for your useful package.
I want to build an advanced search page with several filters like any other multi-filter search.
but unfortunately, I become confused when I read the documentation.
so I will appreciate have some explanation of how to write a multi-filter search.
for instance, I have a shop and sell some shoes. I have 4 types of filters: 

1) exactly match filters => color of shoes, size of shoes.... (I have **Several** filters that should be matched.)
2) similar match filters  => title of shoes
3) range filters              => range of 100$ to 200$ price and **at the same time** added to store from 3 months ago until now.(2020-09-01 09:18:09 to 2020-12-01 11:09:23)
4) sorting filters            => sort the result by price **and at the same time** sort by DateTime of created_at.

Could anyone please write a complete example that contains all of the filters?

Thanks.

**Comment by mohammadjavadz** [comment]
> Hi
> Thanks for your useful package.
> I want to build an advanced search page with several filters like any other multi-filter search.
> but unfortunately, I become confused when I read the documentation.
> so I will appreciate have some explanation of how to write a multi-filter search.
> for instance, I have a shop and sell some shoes. I have 4 types of filters:
> 
> 1. exactly match filters => color of shoes, size of shoes.... (I have **Several** filters that should be matched.)
> 2. similar match filters  => title of shoes
> 3. range filters              => range of 100$ to 200$ price and **at the same time** added to store from 3 months ago until now.(2020-09-01 09:18:09 to 2020-12-01 11:09:23)
> 4. sorting filters            => sort the result by price **and at the same time** sort by DateTime of created_at.
> 
> Could anyone please write a complete example that contains all of the filters?
> 
> Thanks.

One more question: can I implement all of these 4 filters in a single query or should implement them separately?

**Comment by chrisgrim** [comment]
Hi,
I had a similar issue and babenkoivan helped me by adding if statements.
```
$searchRequest = Event::boolSearch()
        ->must('range', ['yourDatesField' => [ 'gte' => 3 months ago ,'lte' => now]]);
        ->must('match', ['shoecolor' => green])
        ->must('match', ['shoesize' => 13]);

if ($request->price) {
            $searchRequest->must('range', ['pricerangefieldhere' => [ 'gte' => $100 ,'lte' => $200]]);
}

$searchedevents = $searchRequest->sort('price', 'desc')
        ->paginate(20);
```
Hope this helps get you in the right direction

**Comment by mohammadjavadz** [comment]
@chrisgrim 
thank you for your reply
I just try to write my queries like you but there are several bugs.
for example when I use one "must" everything is ok but if I add another my result will be zero! (i check the database and indexed documents and the data is valid and exists.)
or when I write like this everything is ok  and the result will be returned:
`$searchResult = Position::boolSearch()
->filter('term', ['gender' => $request->gender])
->paginate(20);`

 but in this case nothing return:

`$searchResult = Position::boolSearch();
$searchResult->filter('term', ['gender' => $request->gender])
->paginate(20);`



are you sure this kind of syntax for the multi clause is valid?
which package do you use? (elastic-scout-driver or both of elastic-scout-driver and plus)?

**Comment by chrisgrim** [comment]
Hi @mohammadjavadz 
I am using driver and plus. I did some testing and discovered that when you do 
```
$searchResult = Event::boolSearch(); $searchResult->filter('term', ['rank' => $request->keywords])->paginate(20);
return $searchResult;
```
This is giving me the error Response::setContent() must be of the type string or null, object given. So I believe that means it is trying to return it as json? I am not exactly clear on this. However in order to get it working you need to do 
```
$searchResult = Event::boolSearch(); $searchResult->filter('term', ['rank' => $request->keywords]);
return $searchResult->paginate(20);
```
this returns it correctly and should work. It also should allow you to stack
```
$searchResult = Event::boolSearch(); $searchResult->filter('term', ['rank' => $request->keywords]);

$searchResult->filter('term', ['otherfield' => $request->keywords]);

return $searchResult->paginate(20);
```
Let me know how it works.

**Comment by mohammadjavadz** [comment]
dear @chrisgrim 
unfortunately, none of them are working.
I am totally confused about the logic behind these queries.
the results are not predictable and behave strangely!
and I don't have any idea how can I debug it.
All of the data are store in MySQL correctly and indexed to elastic search without any error.
I can fetch them and index them by laravel scout import command.

**Comment by chrisgrim** [comment]
Hmm I guess @babenkoivan might have a better explanation. Sorry I couldn't help more.

**Comment by mohammadjavadz** [comment]
dear @chrisgrim 
thanks a lot for your attention and guidance.
I hope to find a solution as soon as possible and share it here.

**Comment by chrisgrim** [comment]
@mohammadjavadz 
@babenkoivan just released a new update that has when() searches! 
https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/generic-methods.md#when
This might be a solution for your problem.
