### ISSUE TITLE
Using boost with the join() for multi-indices

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/elastic-scout-driver-plus#40]
Hi @babenkoivan 
I am doing a multi-indices
```
if ($request->keywords) {
            $searchResult = CityList::multiMatchSearch()
            ->join(Event::class)
            ->join(Organizer::class)
            ->fields(['name', 'name._2gram','name._3gram'])
            ->query($request->keywords)
            ->type('bool_prefix')
            ->sort('rank', 'desc')
            ->execute();
            return $searchResult->models();
        }
```
and I was wondering if there was anyway to boost one index over another? For example an Event result will always return before a CityList even if the city list rank is higher. (The rank would hopefully still work for any listings of the same model.)

**Comment by chrisgrim** [comment]
@babenkoivan How does the multi indices search work? Is there a way to attach a boost to a different model?

**Comment by chrisgrim** [comment]
I think what I am looking for is a way to implement https://www.elastic.co/guide/en/elasticsearch/reference/7.10/search-multiple-indices.html#index-boost

**Comment by babenkoivan** [comment]
Hi @chrisgrim, you are right, you need index boost. Unfortunately, it's not yet supported. I've noted it as a feature request.

**Comment by chrisgrim** [comment]
@babenkoivan Perfect! Thanks so much

**Comment by babenkoivan** [comment]
I've just noticed, that you sort by custom `rank` field, index boost would only help you if you would sort by the score. 

You can try to add a new field in `toSearchableArray` (some fixed `priority` value for each model) and then modify the sorting to:

```php
->sort('priority', 'asc') // records with priority 1 are the first, then goes 2, etc.
->sort('rank', 'desc')
```

**Comment by chrisgrim** [comment]
I was wondering about doing that but didn't know if that was an "incorrect" way of doing things.

**Comment by babenkoivan** [comment]
Also if you don't use pagination, you can grab all the models and then split them into 2 groups by using `groupBy` with a callback.

**Comment by chrisgrim** [comment]
I will have to experiment with that!

**Comment by babenkoivan** [comment]
Hey @chrisgrim, just wanted to let you know, that index boosting is available since [v1.16.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.16.0). You can use new `boostIndex` method as described [here](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/generic-methods.md#boostindex).

**Comment by chrisgrim** [comment]
@babenkoivan 
Amazing!! I can't wait to test this out. Thanks so much for all your work. Do you have a buymeacoffee?

**Comment by babenkoivan** [comment]
Hey @chrisgrim, haven't heard about this service before 🙂 Thanks for the hint! I've added the button in README.
