### ISSUE TITLE
[Question] List data from load() method

### ISSUE THREAD

**Issue by filippesic** [babenkoivan/elastic-scout-driver-plus#42]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.4.13
| Elasticsearch            | 7.9.1
| Laravel                      | 8.15.0
| Laravel Scout           | 8.4.0
| Elastic Scout Driver | 1.2.0
| Elastic Scout Driver Plus | 1.13.0

```
public function getStrictData()
    {
        return File::matchPhrasePrefixSearch()->field('ocr_text')
            ->load(['year'])
            ->query(request('searchInput'))
            ->slop(1)
            ->maxExpansions(10)
            ->highlight('ocr_text')
            ->paginate(24)
            ->withPath(env('APP_URL') . '/search')
            ->appends(['searchInput' => \request('searchInput')]);
    }
```
So I put the result in a variable and send it to blade, How can I access all the years from all files? I used something like this `@foreach((collect($searchedStrictData->items())->map->model()) as $file)`, but it really seems like it's not supposed to be used like that. This works without `load()` method, so is there a more efficient way of doing this?
To be more precise, what I actually want to do is to group search results as years, then each year will lead to files it has.

Any help is enormously appreciated.

**Comment by babenkoivan** [comment]
Hey @filippesic, is `year` a model? Currently you can only paginate matches, which means that paginator has matches as items. What you do is correct, but I think it can be simplified to: 

```php
@foreach($searchedStrictData as $match)
    @php $file =  $match->model(); @endphp
@endforeach
```

There will be an option to paginate only models or have an easy access to models from the existing pagintaor, but this will be released only next year.

**Comment by filippesic** [comment]
@babenkoivan That's correct. File has `year_id` and a `year` (one-to-many)relationship. Yes I did try your way, but I decided to use the 'uglier' one, because it would kinda be with less repetition with $match->model()->somePropertyOrMethod.
For the `year` listing I guess I could just do a collection from `$match->model()->year` and get unique values from it.

**Comment by filippesic** [comment]
Can I just take a minute more of your time? From the my method above, is there a way to list all the `years` from `files`, AKA list data from `loaded` relationship? I don't see the advantage or difference between `load()` and `models()`.
It works like this, but I'm sure that's wrong..
```
$searchedStrictData = $this->getStrictData();
$years = collect(collect($searchedStrictData->items())->map->model())->map->year->unique();
```
Hopefully I'm not being too annoying.

**Comment by babenkoivan** [comment]
Hey @filippesic, `load` and `models` are different. `load` allows you to lazy load relations, `models` helps to retrieve entities, which are relevant to the search results. If you do `models` without loading the relations before, then you get `n+1` database queries. By using `load`, you reduce the number of database queries to 2.

`$years = collect(collect($searchedStrictData->items())->map->model())->map->year->unique();` this doesn't look fancy, but I don't know the better way to do what you want at the moment.

**Comment by filippesic** [comment]
@babenkoivan Thank you for the clarification! :)
