### ISSUE TITLE
Soft Deleted events still appearing in search

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/elastic-scout-driver-plus#44]
Software | Version
-- | --
PHP | 7.4.7
Elasticsearch | 7.3.2
Laravel | 8.15.0
Laravel Scout | 8.5.0
Elastic Scout Driver | 1.2.1

**Describe the bug**
When I delete an event with soft delete and then do a search it still returns that event. The search code I am using 
```
$searchResult = Event::multiMatchSearch()
            ->join(Organizer::class)
            ->join(Category::class)
            ->join(Genre::class)
            ->join(CityList::class)
            ->fields(['name', 'name._2gram','name._3gram'])
            ->query($request->keywords)
            ->analyzer('rebuilt_english')
            ->type('bool_prefix')
            ->execute();
            return $searchResult->matches();
```
and when I search for "tentland" it will return 
```
document: Object
content: Object
category_id: 12
closingDate: "2020-12-18 00:00:00"
genres: Array(1)
hasLocation: true
location_latlon: Object
name: "tentland"
priceranges: Array(1)
priority: 5
published_at: "2020-12-16 19:26:26"
rank: 1
shows: Array(2)
showtype: "s"
status: "p"
__soft_deleted: 1
```

**Expected behavior**
If it has __soft_deleted: 1 I expect it to not appear unless asking for deleted files.

**Comment by chrisgrim** [comment]
I also tried 
```
$searchResult = Event::matchSearch()
            ->field('name')
            ->query($request->keywords)
            ->execute();
            return $searchResult->matches();
```
and I still get the soft_deleted event returned

**Comment by chrisgrim** [comment]
I was able to do a quick fix by going to config/scout.php and turning 'soft_delete' => true to 'soft_delete' => false and then remigrating everything over again.

**Comment by babenkoivan** [comment]
Hey @chrisgrim, it's not a bug.  Full text queries do not support the filter context, so it's not possible to exclude soft deleted records from the search results. If you want to use soft deletes, you need to make a  [boolean query](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/compound-queries.md#boolean).

**Comment by chrisgrim** [comment]
Oh gotcha! Thanks!
