### ISSUE TITLE
Issue sorting when joining multiple indices

### ISSUE THREAD

**Issue by chrisgrim** [babenkoivan/elastic-scout-driver-plus#45]
Hi,
I have a general search bar on my site that I want to search multiple indices. A user can start typing and it will search through an index of events, organizers and cities. 
I have got this working fairly well with 
```
$searchResult = Event::multiMatchSearch()
            ->join(Organizer::class)
            ->join(CityList::class)
            ->fields(['name', 'name._2gram','name._3gram'])
            ->query($request->keywords)
            ->analyzer('rebuilt_english')
            ->type('bool_prefix')
            ->execute();
            return $searchResult->matches();
```
The problem I am having is when I try to add a sort to the mix. If a user types in "los" the top three results are
```
East London, ZA
East Los Angeles, CA
Gamping Lor, ID
```
I realize I need to sort by population however when I do
```
if ($request->keywords) {
            $searchResult = Event::multiMatchSearch()
            ->join(Organizer::class)
            ->join(CityList::class)
            ->fields(['name', 'name._2gram','name._3gram'])
            ->query($request->keywords)
            ->analyzer('rebuilt_english')
            ->type('bool_prefix')
            ->sort('population', 'desc')
            ->execute();
            return $searchResult->matches();
```
it only returns cities with the top results being
```
London GB, 
Los Angeles, CA
```
but if I search for an event or organizer nothing is returned. 

Is there any way to add a sort to the results from a specific index? Is there a better way I should be doing this search?

**Comment by babenkoivan** [comment]
Hi @chrisgrim, I think nothing is returned because `population` doesn't exist in other 2 indices. You might try to use `sortRaw` as follows:

```php
$searchResult = Event::multiMatchSearch()
    // ...
    ->searchRaw([['population' => ['order' => 'desc', 'ignore_unmapped' => true]]])
    // ...
```

`ignore_unmapped` should do the trick. I hope this helps 🙂

**Comment by chrisgrim** [comment]
Hi @babenkoivan 
Im guessing you meant sortRaw instead of searchRaw in your example. However, when I tried
```
 $searchResult = Event::multiMatchSearch()
            ->join(Organizer::class)
            ->join(Category::class)
            ->join(Genre::class)
            ->join(CityList::class)
            ->fields(['name', 'name._2gram','name._3gram'])
            ->query($request->keywords)
            // ->analyzer('rebuilt_english')
            ->type('bool_prefix')
            ->sortRaw([['population' => ['order' => 'desc', 'ignore_unmapped' => true]]])
            ->execute();
            return $searchResult->matches();
```
I got the error
```
message: "{"error":{"root_cause":[{"type":"x_content_parse_exception","reason":"[1:147] [field_sort] unknown field [ignore_unmapped]"}],"type":"x_content_parse_exception","reason":"[1:147] [field_sort] unknown field [ignore_unmapped]"},"status":400}
```

**Comment by babenkoivan** [comment]
> Im guessing you meant sortRaw instead of searchRaw in your example

Yes, sorry for the confusion 🙂

> I got the error

It looks like `ignore_unmapped` has been deprecated, can you try `sortRaw([['population' => ['order' => 'desc', 'unmapped_type' =>'integer']]])` instead? Make sure, that `unmapped_type` value corresponds `population` field type.

**Comment by chrisgrim** [comment]
That worked so well!!
Thanks so much @babenkoivan
