### ISSUE TITLE
support for aggregations

### ISSUE THREAD

**Issue by oknoote** [babenkoivan/elastic-scout-driver-plus#5]
@babenkoivan Is it possible to get support for aggregations for the rawSearch method? 

An example query with aggregations on a field named "instruments":

```
{
    "from": 0,
    "size": 5,
    "aggs": {
        "instruments": {
            "terms": {
                "field": "instruments"
            }
        }
    },
    "query": {
        "multi_match": {
            "query": "bass",
            "fields": [
                "instrument",
                "bio"
            ]
        }
    }
}
```

**Comment by babenkoivan** [comment]
Hi @oknoote, it's planned to add the aggregations support, but I wouldn't expect it to be delivered before mid of July.

**Comment by oknoote** [comment]
Thank you, I will look for a fix in the mean time!

**Comment by oknoote** [comment]
Btw. method SearchRaw in the previous package (scout-elastic) did support this but it seems the new RawSearch method is more specific in its methods (which is fine, of course). For now I'll probably revert to the ElasticSearch client for Raw queries with aggregations as a workaround. Do you maybe have a quick example of how I could invoke the ElasticSearch client directly from a controller?

**Comment by babenkoivan** [comment]
@oknoote, you should be able to inject the client in a controller like following:

```
class MyController
{
    public function __construct(\Elasticsearch\Client $client) 
    {
    }
}
```

**Comment by oknoote** [comment]
Thanks I got it to work, including aggregations! Was working with a lot of raw results already previously so this is fine for now, just a few minor query changes. When the aggregations functionally has been added I'll switch back to using the rawSearch method. Thanks for all the effort towards making these great packages, much appreciated!

**Comment by babenkoivan** [comment]
Hey @oknoote, the aggregations support was added in [v1.3.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.3.0). Please update the package via composer and check the README file for the usage examples.

**Comment by oknoote** [comment]
Amazing, thank you!
