### ISSUE TITLE
How to add top_level track_scores parameter?

### ISSUE THREAD

**Issue by robigoal** [babenkoivan/elastic-scout-driver-plus#50]
Hi,

I want to add _track_scores_ in the rawSearch method to get a score on the hits when we are not sorting by relevance. Is this possible?

**Comment by babenkoivan** [comment]
Hi @robigoal, it's possible since [v1.16.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.16.0). Please, check the documentation [here](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/generic-methods.md#trackscores).
