### ISSUE TITLE
Paginate with Laravel JsonResource

### ISSUE THREAD

**Issue by ybert** [babenkoivan/elastic-scout-driver-plus#54]
First of all, thank you very much for your incredible work.
I was a user of scout-elasticsearch-driver and I try to migrate to the new packages.

| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.3.22
| Elasticsearch            | 7.9.2
| Laravel                      | 6.20.8
| Laravel Scout           | 8.6.0
| Elastic Scout Driver | 1.2.2
| Elastic Scout Driver Pus | 1.17.0

**Describe the bug**
I try to paginate results from elasticsearch and use this directly in a Laravel API Resource as these resources take advantage of paginated results by automatically fill meta data (pagination next, prev, last, first, etc...) for the api resource.
I get this error : Call to undefined method ElasticScoutDriverPlus\Paginator::first() 

**To Reproduce**
In my Controller : 
```
    public function search(Request $request)
    {
        $routes = Route::boolSearch()->must('multi_match', [
            'type' => 'phrase',
            'query' => 'Lac des Minimes',
            'fields' => ['name^3', 'keyword']
        ])->load(['activity', 'user', 'shape', 'trademark', 'elevation'])->paginate(10);

        $routes->models();

        return RouteResource::collection($routes);
    }
```

RouteResource : 
```
class RouteResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->resource->id,
            'created_at' => $this->resource->created_at,
            'name' => $this->resource->name
        ];
    }
}
```

**Current behavior**
I get this error : Call to undefined method ElasticScoutDriverPlus\Paginator::first() 

I think it is because of the structure of items in elastic paginator . The Eloquent Collection must be at the root items in ElasticScoutDriverPlusPaginator. 
```
ElasticScoutDriverPlus\Paginator {#363 ▼
  -searchResult: ElasticScoutDriverPlus\SearchResult {#367 ▶}
  #total: 1
  #lastPage: 1
  #items: Illuminate\Support\Collection {#424 ▼
    #items: array:1 [▼
      0 => ElasticScoutDriverPlus\Match {#423 ▼
        -lazyModelFactory: ElasticScoutDriverPlus\Factories\LazyModelFactory {#365 ▼
          -modelScope: ElasticScoutDriverPlus\Support\ModelScope {#360 ▶}
          -mappedIds: array:1 [▶]
          -mappedModels: array:1 [▼
            "route_index_v3" => Illuminate\Database\Eloquent\Collection {#439 ▶}
          ]
        }
        -hit: ElasticAdapter\Search\Hit {#366 ▼
          -hit: array:5 [▶]
        }
      }
    ]
  }
  #perPage: 10
  #currentPage: 1
  #path: "https://api.localhost/api/v2/routes"
  #query: []
  #fragment: null
  #pageName: "page"
  +onEachSide: 3
  #options: array:2 [▶]
}
```

**Expected behavior**
If I replace  the search method in my Controller by the following, I get no error. I expect the same with Elastic Paginator.

```
public function search(Request $request)
    {
        Route::query()->paginate(10);

        return RouteResource::collection($routes);
    }
```

We should be able to call a resource with a paginated results as we can see on Laravel documentation : https://laravel.com/docs/8.x/eloquent-resources#pagination

**Comment by babenkoivan** [comment]
Hi @ybert, thank you for reporting the issue!

First of all, it's intended, that `Paginator` has `Matches` as items, but there was a bug, which is fixed now in [v1.18.1](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v1.18.1).

Second, as `Paginator` paginates `Matches` and not `Models`, you should adjust your resource accordingly:

```php
class RouteResource extends JsonResource
{
    public function toArray($request)
    {
        $model = $this->resource->model(); 

        return [
            'id' => $model->id,
            'created_at' => $model->created_at,
            'name' => $model->name
        ];
    }
}
```

Alternatively, you can try to replace `Paginator` collection in your controller:

```php
public function search(Request $request)
    {
        $routes = Route::boolSearch()->must('multi_match', [
            'type' => 'phrase',
            'query' => 'Lac des Minimes',
            'fields' => ['name^3', 'keyword']
        ])->load(['activity', 'user', 'shape', 'trademark', 'elevation'])->paginate(10);

       $routes->setCollection($routes->models());

        return RouteResource::collection($routes);
    }
```

I hope it helps 🙂

**Comment by ybert** [comment]
Thank you it helps a lot.
You saved my day (maybe my week) ! :)

I prefer the solution with call to setCollection as Resource can be used by other code that provide simple Laravel Paginator.

**Comment by babenkoivan** [comment]
Hey @ybert, glad that I could help.

Maybe if you have time, you could create a wiki page in this project and explain in examples how to use pagination with `JsonResource`. I'd be happy to add the link to the documentation.

**Comment by igor-kamil** [comment]
+1 
this could be part of documentation

**Comment by ybert** [comment]
> +1 this could be part of documentation

You can find here : https://github.com/babenkoivan/elastic-scout-driver-plus/wiki/Paginated-Resources

**Comment by ybert** [comment]
@igor-kamil You can find it here : https://github.com/babenkoivan/elastic-scout-driver-plus/wiki/Paginated-Resources
