### ISSUE TITLE
Search query options missing

### ISSUE THREAD

**Issue by luciegirard** [babenkoivan/elastic-scout-driver-plus#59]
Hello (again) :-)  ,
I'm dealing with a problem, in fact I'm trying to add filtering options after using a search query like `with()`, `withCount()`, `load()`.
Elastic Scout Driver permits to do it because it uses the builder from Laravel\Scout\Builder but Elastic Scout Driver Plus does not use it and using `with()` or `withCount()` functions is impossible.
It is says that Elastic Scout Driver Plus library doesn't work without Elastic Scout Driver and extends standard Scout search capabilities by introducing advanced query builders, so why is it not possible to use functions from Laravel\Scout ?
Also, I'm confuse about seeing that `load` function used in Elastic Scout Driver Plus has been rewrite in the Elastic Scout Driver Plus library and applied `with` function in reality[1], isn't it easier to use the Laravel\Scout library ?

Thanks in advance

[1] https://github.com/babenkoivan/elastic-scout-driver-plus/blob/9217d025bca263ee806d87b23b263ba51f69c9c4/src/Builders/SearchRequestBuilder.php#L199

**Comment by babenkoivan** [comment]
Hey @luciegirard, can you please add a code example, so I could better understand what are you trying to achieve?

Elastic Scout Driver Plus uses query DSL builders, which of course differ from standard Scout builder. It would be impossible to add all the features Elastic Scout Driver Plus provides with the default builder.

**Comment by luciegirard** [comment]
I realize I wasn't very clear in my explanation, so what I do not understand is, when I retrieve Eloquent models with results' ids from Elasticsearch, why is it not possible to add a query builder function to enrich data returned by this Eloquent query (similar as this issue[1]).
As said in the issue linked, the fifth version resolves the problem by adding the `query` function allowing to add anything we would like to the query builder like `with()` or `withCount()`.
But the problem is that we have no access to the query builder in Elastic Scout Driver Plus.
The only available function is `load()` allowing to load a type with `with()` function which questions me about why is it not called `with()`.
And I'm blocked because I'm trying to use `withCount` function but without having access to the query builder I can not do it.

[1] https://github.com/laravel/scout/pull/290

**Comment by babenkoivan** [comment]
This package is a bit more than a regular Scout driver, it offers a lot, but also limits in some ways. Due to lazy loading and possible caching, it's not that easy to provide full control over the query.
 
The good thing, you can always retrieve models and than enrich your data:

```php
$models = $searchResult->models();

$models->loadCount('my_relation');
$models->load('my_relation');
```

Similarly to `withCount` method, Eloquent will make a single query to fetch the requested data.

**Comment by luciegirard** [comment]
Thanks for your answer and your work, it will help !
