### ISSUE TITLE
boolSearch query returns 0 result

### ISSUE THREAD

**Issue by bekee** [babenkoivan/elastic-scout-driver-plus#60]
I've had a hard time trying to figure out why bool queries ain't working.

A query as simple as

 $searchResult = BusinessListing::boolSearch()
    ->must('match_all')
    ->withTrashed()
    ->execute();

returns zero result.

Please I need help

**Comment by bekee** [comment]
Confusingly all boolean quries I run in kibana returns result. i can't tell what I'm doing wrong I've also upgraded to version 2.0.0 of this package and I'm using elasticsearch version 7.3.2.

I'm really confused I need help

**Comment by bekee** [comment]
I noticed that if I use paginate in place of execute, I get results I don't know why but I'm getting expected results

**Comment by bilalswiftsolutions** [comment]
I am facing same issue . paginate is working execute is not working @babenkoivan

**Comment by babenkoivan** [comment]
Hi @bilalswiftsolutions, can you help me to analyze the issue? Is it possible, that you get the content of the `$params` array in the `DocumentManager::search()` method and compare the difference?
