### ISSUE TITLE
Search and paginate over 10000 records

### ISSUE THREAD

**Issue by luciegirard** [babenkoivan/elastic-scout-driver-plus#61]
Hello @babenkoivan
Sorry to bother you again, but I'm trying to searching over 10000 records and I've seen that scrolling is not available on your package.
The question that I'm asking relates to this issue that have been closed automatically without answer : https://github.com/babenkoivan/elastic-scout-driver-plus/issues/49#issue-791939541.
I've seen in your older version of Elastic Scout Driver that you were considering implementing scroll in this version[1]. Is it still planed ?
Thanks for your work.

[1] https://github.com/babenkoivan/scout-elasticsearch-driver/issues/83#issuecomment-383015549

**Comment by babenkoivan** [comment]
Hey @luciegirard, 

I do not plan to implement scroll search at the moment. Maybe if I get many requests in the future, I'll change my mind. 
Not sure if this would help, but you can adjust `max_result_window` to increase the number of documents returned.

**Comment by danielmcguinness** [comment]
@babenkoivan Thanks for this excellent library, its really nice to work with. I would like to see scroll implemented if possible. Our use case is exporting data to excel, where we can have many records.

Thanks for all your efforts!

**Comment by babenkoivan** [comment]
Hey @danielmcguinness, I'll consider including this feature in the next version 🙂

**Comment by petsoukos** [comment]
Is there a way to paginate over 10000 records with the current implementation? Some kind of strategy to fetch the next set of 10k documents? With default paginator or even without, using a custom implementation?

**Comment by nicopenaredondo** [comment]
Looking for this feature as well.

**Comment by petsoukos** [comment]
@nicopenaredondo You could set the "max_result_window" higher than the default 10.000, but use it with care since it can overwhelm your ES instance

**Comment by vukhacbiet** [comment]
Hi @babenkoivan 
Could you  plan to implement scroll feature to this package.
I think we always have times need to search in a larger than 10000 rows data :D

**Comment by babenkoivan** [comment]
Hi @vukhacbiet, you can use [search after](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/available-methods.md#searchafter) if you need to retrieve more than 10000 hits.

**Comment by hamdallah90** [comment]
> Hi [@babenkoivan](https://github.com/babenkoivan) Could you plan to implement scroll feature to this package. I think we always have times need to search in a larger than 10000 rows data :D
+1
