### ISSUE TITLE
Cannot pass mocked model for unit testing to SearchRequestBuilder

### ISSUE THREAD

**Issue by rrolla** [babenkoivan/elastic-scout-driver-plus#65]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.4.16
| Elasticsearch            | 7.7.0
| Laravel                      | 8.38.0
| Laravel Scout           | 8.6.1
| Elastic Scout Driver | 2.0

**Describe the bug**

Cannot pass in a mocked model to SearchRequestBuilder
Also tried this with no luck
```php
$employeeMock->shouldReceive('__construct')->once()->andReturnSelf();
```

**To Reproduce**

Create file TestEmployeeModelTest.php in tests directory with content below and run tests for it
```php
<?php

class TestEmployeeModel extends \Illuminate\Database\Eloquent\Model
{
    use \Laravel\Scout\Searchable;
    use \ElasticScoutDriverPlus\QueryDsl;

    public function employees(): \ElasticScoutDriverPlus\Builders\SearchRequestBuilder
    {
        return $this->rawSearch()->query(['match_all' => new \stdClass()]);
    }
}

class TestEmployeeModelTest extends \Tests\TestCase
{
    public function testItShouldCallEmployees(): void
    {
        $queryBuilderInterface = \Mockery::mock(\ElasticScoutDriverPlus\Builders\QueryBuilderInterface::class);
        $employeeMock = \Mockery::mock(TestEmployeeModel::class)->makePartial();
        \Mockery::mock(new \ElasticScoutDriverPlus\Builders\SearchRequestBuilder($employeeMock, $queryBuilderInterface));
        $employeeMock->shouldReceive('rawSearch')->once();

        $employeeMock->employees();
    }
}

```

```php
vendor/bin/phpunit ./tests/TestEmployeeModelTest.php
```

**Current behavior**

it throw error:
```php
1) TestEmployeeModelTest::testItShouldCallEmployees
Mockery\Exception\BadMethodCallException: Received Mockery_1_TestEmployeeModel::__construct(), but no expectations were specified

/var/www/vendor/babenkoivan/elastic-scout-driver-plus/src/Support/ModelScope.php:45
/var/www/vendor/babenkoivan/elastic-scout-driver-plus/src/Support/ModelScope.php:36
/var/www/vendor/babenkoivan/elastic-scout-driver-plus/src/Builders/SearchRequestBuilder.php:83
/var/www/tests/Unit/Services/Repositories/Search/Employee/SimpleUnitTest.php:20

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

**Expected behavior**

It should go further than this step eg incorrect return type

**Comment by babenkoivan** [comment]
Hey @rrolla, I've removed `final` keyword from `SearchRequestBuilder` in `v2.0.1`, now you can do something like:

```php
class TestEmployeeModelTest extends \ElasticScoutDriverPlus\Tests\Integration\TestCase
{
    public function testItShouldCallEmployees(): void
    {
        $searchRequestBuilder = \Mockery::mock(\ElasticScoutDriverPlus\Builders\SearchRequestBuilder::class);
        $searchRequestBuilder->shouldReceive('query')->once()->with(['match_all' => new \stdClass()])->andReturnSelf();

        $employeeMock = \Mockery::mock(TestEmployeeModel::class)->makePartial();
        $employeeMock->shouldReceive('rawSearch')->once()->andReturn($searchRequestBuilder);

        $employeeMock->employees();
    }
}
```

I hope this helps 🙂

**Comment by rrolla** [comment]
Thanks @babenkoivan for the update, I solved the problem differently thanks to this article https://tomasvotruba.com/blog/2019/03/28/how-to-mock-final-classes-in-phpunit/

**Comment by nicopenaredondo** [comment]
Hi @rrolla , Do you have some code snippets when mocking this classes via http testing ? I do want to test my http test without connecting actually in Elasticsearch.

**Comment by rrolla** [comment]
> Hi @rrolla , Do you have some code snippets when mocking this classes via http testing ? I do want to test my http test without connecting actually in Elasticsearch.

Hey we do something like this:

```php
<?php

declare(strict_types=1);

namespace App\Services\Repositories\Search\Employee;

use App\Models\Employees\Employee;
use ElasticScoutDriverPlus\Paginator;
use stdClass;

class EmployeeSearchDbRepository
{
    private Employee $employeeDataModel;

    public function __construct(Employee $employeeDataModel)
    {
        $this->employeeDataModel = $employeeDataModel;
    }

    public function employees(): Paginator
    {
        $builder = $this->employeeDataModel->boolSearch()
            ->should(['match_all' => new stdClass()]);
        
        return $builder->paginate(25);
    }
}
```

tests
```php

public function testGetSuccessWithSearchEmployeesViewAll(): void
{
    $employeeSearchDbRepositoryMock = Mockery::mock(EmployeeSearchDbRepository::class);

    $result = new TestQueryMatch;
    $searchResult = new SearchResult(collect([$result]), collect([]), collect([]), 1);
    $paginator = new Paginator($searchResult, 2, 1);

    /* we mock call to real elastic */
    $employeeSearchDbRepositoryMock->shouldReceive('employees')->once()->andReturn($paginator);
    $this->swap(EmployeeSearchDbRepository::class, $employeeSearchDbRepositoryMock);
}

class TestQueryMatch
{
    public function document(): object
    {
        return new class {
            public function getId(): int
            {
                return mt_rand();
            }

            public function getContent(): array
            {
                return [
                    'name' => 'Zoe Jones',
                ];
            }
        };
    }
}
```
Hope this will help

**Comment by nicopenaredondo** [comment]
Hi @rrolla, Thanks for the snippets.  Do you have other code snippets for HTTP testing. I'm having a hard time to execute the http testing using this package.

See my code below.

Test
![image](https://user-images.githubusercontent.com/3615451/152516198-2102c0c5-0c45-4150-b4fe-5874efabaed1.png)


Code
![image](https://user-images.githubusercontent.com/3615451/152516225-4bcb245e-494f-4246-b114-53a54c1d0655.png)


Would you suggest that i should implement unit testing for the repository class and http testing for the controllers (just mock the repository class results)?

**Comment by nicopenaredondo** [comment]
> ```
> class TestQueryMatch
> {
>     public function document(): object
>     {
>         return new class {
>             public function getId(): int
>             {
>                 return mt_rand();
>             }
> 
>             public function getContent(): array
>             {
>                 return [
>                     'name' => 'Zoe Jones',
>                 ];
>             }
>         };
>     }
> }
> ```

Hello, Tried using your example. However, I encounter this error.

`TypeError: ElasticScoutDriverPlus\Decorators\SearchResult::__construct(): Argument #1 ($searchResponse) must be of type ElasticAdapter\Search\SearchResponse, Illuminate\Support\Collection given`

**Comment by babenkoivan** [comment]
Hey @nicopenaredondo, there is no an easy, standard way to mock the search response. Perhaps, the simplest solution is to mock `DocumentManager`:

```php
public function test(): void
{
    $mock = $this->createMock(DocumentManager::class);
    
    $mock->method('search')->willReturn([
        /* here goes a raw Elasticsearch response, e.g.:
        [
            'hits' => [
                'total' => [
                    'value' => 1,
                    'relation' => 'eq',
                ],
                'max_score' => 1.601195,
                'hits' => [
                    [
                        '_index' => 'test',
                        '_id' => '1',
                        '_score' => 1.601195,
                        '_source' => ['content' => 'foo'],
                    ],
                ],
            ],
        ]*/
    ]);
    
    $this->app->bind(DocumentManager::class, $mock);
    
    // here goes your other code with the http request
}
```

I didn't test it, but the idea is that `DocumentManager` is mocked in a way that it always returns a needed response.

**Comment by nicopenaredondo** [comment]
> Thanks @babenkoivan for the update, I solved the problem differently thanks to this article https://tomasvotruba.com/blog/2019/03/28/how-to-mock-final-classes-in-phpunit/

Oh god. This is heaven sent. I've managed to use this package also. Thanks @rrolla
