### ISSUE TITLE
Receiving empty response  after using elastic-scout-driver-plus

### ISSUE THREAD

**Issue by bilalswiftsolutions** [babenkoivan/elastic-scout-driver-plus#68]
| Software                   | Version
| --------------------| ---------------
| PHP                           | 7.4
| Elasticsearch            | 7.10
| Laravel                      | 8.2
| Laravel Scout           | 9.0
| Elastic Scout Driver | 1.4

**Describe the bug**
I am trying to search with  `lastic-scout-driver-plus`  but not getting any result response is empty

```
$suggestedAddresses = Address::matchSearch()
        ->field('company_name')
        ->query("{$query}")
        ->fuzziness('AUTO')
        ->size(10)
        ->execute();
```
`Model`
```
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;
use ElasticScoutDriverPlus\QueryDsl;


class Address extends Model
{
    use HasFactory,Searchable,QueryDsl;

    protected $table = 'addresses';
    /**
     * @var array
     */
    protected $guarded = [];


    public function toSearchableArray()
    {
        $array = [];
        $array['id'] = $this->id;
        $array['full_address'] = $this->full_address;
        $array['company_name'] = $this->company_name;
        $array['street_address'] = $this->street_address;
        $array['suburb'] = $this->suburb;
        $array['city'] = $this->city;
        return $array;
    }
}
```

**Current behavior**
Curretnly i am just receiving empty response. But when i use `search()` it gives me result

**Comment by bilalswiftsolutions** [comment]
I see that `paginate` is working but `execute` is not working

**Comment by babenkoivan** [comment]
Hey @bilalswiftsolutions, can you please post the difference of what mentioned [here](https://github.com/babenkoivan/elastic-scout-driver-plus/issues/60)? I believe, that the only difference is that `paginate` defines also the `from` parameter.
