### ISSUE TITLE
Do not attempt to hydrate model when deleting

### ISSUE THREAD

**Issue by robtesch** [babenkoivan/elastic-scout-driver-plus#69]
Not really sure if this is something that is within your control, or it's something that can only be changed by scout itself.

At the moment, when we try to delete a model (and therefore remove it from search), this package goes through the process of calling ->toSearchableArray() on the model(s).

It is my understanding that in order to delete an item from elasticsearch, all that is required is the document id, so there really isn't a need to try and get the model's other attributes.

The only thing I am seeing in the code is that there is also a mention of the routingPath field (which I don't personally use, but might be needed for something else).

As it stands, models are failing to delete from search in some cases because they fail to hydrate properly (since the model no longer exists in the database). Aside from that, calling the database is unnecessary at this point and just causes more work than needed.

If you are in agreement that this is an issue that's worth looking at, I am happy to try and submit a PR.

**Comment by babenkoivan** [comment]
Hi @robtesch, it makes sense, but currently `toSearchableArray` is required to be called when the routing is used. In general, `toSearchableArray` shouldn't add much overhead unless you make database queries in it (e.g. fetching relations). I'll think about how this can be improved, but I'll close https://github.com/babenkoivan/elastic-scout-driver/pull/24 as it cuts off some functionality.

**Comment by robtesch** [comment]
Thanks @babenkoivan, that does make sense. I am sure we can come up with an alternative solution at some point.

**Comment by spiritinlife** [comment]
@babenkoivan  O yes right, somehow i already forgot about that 👍. Well maybe we can pass a `deleting` param to toSearchableArray and let the developers decide what to do with it. In an advanced readme section we could explain that if you use routing the routingPath should be always returned when toSearchableArray is called.

**Comment by babenkoivan** [comment]
@spiritinlife I have some ideas on how to handle it differently and more explicitly to users, but it requires an interface change, so it's not coming until the next major release.
