### ISSUE TITLE
fuzzySearch and boolSearch

### ISSUE THREAD

**Issue by RolandVerner** [babenkoivan/elastic-scout-driver-plus#71]
I am trying to use your library, but I have a question is it possible for some hove to use fuzzySearch with 

  ->should('match', ['name' => 'John'])
  ->should('match', ['title' => 'The Book'])

Form boolSearch

Or

Another way to use bool search but with fuzziness?

Maybe you can help me, I need to make user search like on social networks I already did the transliteration but I need to put the English name and on Russian to one search query

**Comment by RolandVerner** [comment]
Here is my code maybe someone can help.
How I can add here fuzziness

`            $transliterator = new Transliterator(Map::LANG_RU, Map::GOST_7_79_2000);
            $transliterated = $transliterator->make($this->search);
            $search = User::boolsearch();
            $search->should('match', ['full_name' => $this->search]);
                $search->should('match', ['full_name' => $transliterated]);
                $search->should('match', ['email' => $this->search]);
                $search->should('match', ['phone' => $this->search]);
                $search->should('match', ['id' => $this->search]);
                $search->minimumShouldMatch(1);
                $search->withTrashed();
            $users = $search->paginate($this->pagination);
            $users->setCollection($users->models());`

**Comment by babenkoivan** [comment]
Hi @RolandVerner, have you tried `$search->should('match', ['full_name' => ['query' => $this->search, 'fuzziness' => 'AUTO']]);`?

**Comment by RolandVerner** [comment]
> Hi @RolandVerner, have you tried `$search->should('match', ['full_name' => ['query' => $this->search, 'fuzziness' => 'AUTO']]);`?

I will try and give a response thank you

**Comment by RolandVerner** [comment]
> Hi @RolandVerner, have you tried `$search->should('match', ['full_name' => ['query' => $this->search, 'fuzziness' => 'AUTO']]);`?

Yes it helped thanks!
