### ISSUE TITLE
rawSeach + range

### ISSUE THREAD

**Issue by usovichivan** [babenkoivan/elastic-scout-driver-plus#72]
is it possible to combine "match" with "range"  something like this?
$searchResult = Lot1::rawSearch()
                            ->query([
                                'match' => ['body_style' => 'SUV'],
                                "range" => [
                                    "bid" => ["gte" => 1000, "lte" => 10000]
                                ]
                            ])
                            ->aggregate('exterior_color', [
                                'terms' => [
                                    'field' => 'exterior_color',
                                ],
                            ])
                            ->aggregate('drive_train', [
                                'terms' => [
                                    'field' => 'drive_train',
                                ],
                            ])
                            ->size(25)
                            ->execute();

**Comment by babenkoivan** [comment]
Hi @usovichivan, I think a [boolean query](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/compound-queries.md#boolean) would work for you, something like:

```php
$searchResult = Lot1:: boolSearch()
    ->must('match', ['body_style' => 'SUV'])
    ->must('range', ['bid' => ['gte' => 1000, 'lte' => 10000]])
    // -> ...
```
