### ISSUE TITLE
Call to undefined method ScoutElastic\ElasticEngine::executeSearchRequest()

### ISSUE THREAD

**Issue by JieAnthony** [babenkoivan/elastic-scout-driver-plus#75]
```php
$searchResult = Site::fuzzySearch()
            ->field('address')
            ->value('test')
            ->execute();
dd($searchResult);
```
> php 8.0.6
> laravel 8.49.2
> babenkoivan/elastic-scout-driver-plus v2.3.0
> babenkoivan/scout-elasticsearch-driver v4.3.0

RESULT
```
Error: Call to undefined method ScoutElastic\ElasticEngine::executeSearchRequest() in file /www/wwwroot/charger-search-backend/vendor/babenkoivan/elastic-scout-driver-plus/src/Builders/SearchRequestBuilder.php on line 322
```

**Comment by andrey-helldar** [comment]
Me too:

```php
return User::matchSearch()
    ->source(['phone', 'first_name', 'last_name'])
    ->operator('AND')
    ->query($query)
    ->paginate(50);
```

Result:
```
Call to undefined method ElasticScoutDriver\\Engine::executeSearchRequest()
```

**Comment by JieAnthony** [comment]
@andrey-helldar Do you have "babenkoivan/scout-elasticsearch-driver" package in the composer.json?

**Comment by andrey-helldar** [comment]
@JieAnthony, no, there is only:

```json
"babenkoivan/elastic-migrations": "^1.6",
"babenkoivan/elastic-scout-driver-plus": "^2.3",
```

**Comment by andrey-helldar** [comment]
In my case, the error was that the auto-discover did not work. I am using Lumen.

**Comment by JieAnthony** [comment]
@andrey-helldar
 i am using Laravel.
It will work when I delete the "babenkoivan/scout-elasticsearch-driver" package, I hope it can help you

**Comment by peektoseen** [comment]
> @andrey-helldar Do you have "babenkoivan/scout-elasticsearch-driver" package in the composer.json?

Hello! I have same issue, but this package installed in composer.json.
"Call to undefined method ScoutElastic\\ElasticEngine::executeSearchRequest()"
Maybe I need switch search engine? With elastic-scout-driver all work fine, but with elastic-scout-driver-plus - nope :(
Please give me some advice.

**Comment by peektoseen** [comment]
My bad. After delete **babenkoivan/scout-elasticsearch-driver** all work fine.

**Comment by JieAnthony** [comment]
> My bad. After delete **babenkoivan/scout-elasticsearch-driver** all work fine.

if you have **babenkoivan/scout-elasticsearch-driver**  package, delete it is the answer to this issue
