### ISSUE TITLE
Query on multiple values using boolSearch filter

### ISSUE THREAD

**Issue by tmuzanenhamo** [babenkoivan/elastic-scout-driver-plus#77]
Hi I am trying to filter on multiple temrs/ values using the filter on boolSearch

$builder = LuxityProduct::boolSearch();
        $builder->filter('terms',  ['luxity_brand_id' => [2, 8]]);
        
the above query works.

The one below here returns an empty array

$builder = LuxityProduct::boolSearch();
        $builder->filter('terms',  ['category_type' => ['ACCESSORIES', 'SHOES']]);
        

What could be the issue or what is the best way to query on multiple string values

**Comment by babenkoivan** [comment]
Hey @tmuzanenhamo, please check your mapping. I believe `category_type` must be defined as a `keyword`.
