### ISSUE TITLE
Use extra request body search fields

### ISSUE THREAD

**Issue by AndreyLanko** [babenkoivan/elastic-scout-driver-plus#79]
Hi is there any option to use script_fields for rawSearch() described here
https://www.elastic.co/guide/en/elasticsearch/reference/7.0/search-request-script-fields.html

**Comment by codana-user** [comment]
@AndreyLanko did you find a solution for this?

**Comment by babenkoivan** [comment]
@codana-user, you can create a feature request if you need script fields support 🙂
