### ISSUE TITLE
Using scope in queries. 

### ISSUE THREAD

**Issue by peektoseen** [babenkoivan/elastic-scout-driver-plus#80]
Hi all!
When I use elastic-scout-driver - I can add model scopes to the result, like this:

```php
$elements = Book::search('food')->query(function ($query) {
    return $query->BySubscription()->ByData();
})->paginate(
    24
);
```

But what If I need using elastic-scout-driver-plus  with **boolSearch** ?
Is exist some method for do it?

**Comment by babenkoivan** [comment]
Hey @peektoseen, `query` is currently not supported by `elastic-scout-driver-plus`.

**Comment by Stalex89** [comment]
@babenkoivan Hello, may I ask if this feature is expected in the nearest future ? I really need it for my project

I have users with subscriptions, and I need to filter users with no active subscription out of elasticsearch query. I have a scope with eloquent relation, but I cannot use it together with searchQuery.

Thank you in advance!

**Comment by babenkoivan** [comment]
Hey @Stalex89 and @peektoseen, you can use the `refineModels` method as described [here](https://github.com/babenkoivan/elastic-scout-driver-plus/blob/master/docs/available-methods.md#refinemodels).
