### ISSUE TITLE
Write and BulkWrite metods

### ISSUE THREAD

**Issue by masterjus** [babenkoivan/elastic-scout-driver-plus#81]
Hello @babenkoivan 

I look at your library and it's cool!

One thing prevents me to use it - I can't fill the index by using it.

If you could add methods that may fill an index (such as `write`, `bulkWrite`, `reindex`) it would be perfect.

Cheers.

**Comment by babenkoivan** [comment]
Hey @masterjus, you can create an index by using https://github.com/babenkoivan/elastic-migrations and then import your data with standard Scout functionality https://laravel.com/docs/8.x/scout#batch-import.
