### ISSUE TITLE
Field Weight

### ISSUE THREAD

**Issue by tcagkansokmen** [babenkoivan/elastic-scout-driver-plus#84]
Hi there,

Is that possible to make "field weight" on multiMatchSearch fields?

for example; if query is matches on Title so it will have more score, description is lower, details is lower.

How can we arrange it?

**Comment by mofolo** [comment]
You can do something already using a bool search like so:
In my case I'm searching for a customer's name.

$json = ['bool' => 
            ['should' => [ 
                ['match_phrase' => 
                    ['full_name' => ['query' => $query, 'boost' => 5]]
                ],
                ['match_phrase_prefix' => 
                    ['full_name' => ['query' => $query, 'boost' => 2]]
                ],
                ["match" => 
                    ['full_name' => ['query' => $query, 'boost'=>2]]
                ],
                ["match" => 
                    ['email' => ['query' => $query, 'boost'=>1]]
                ],
                ["match" => 
                    ['description' => ['query' => $query, 'boost'=>1]]
                ]
            ]
        ]
    ];

\App\Customer::rawSearch()->query($json)->raw();

**Comment by babenkoivan** [comment]
Hi @tcagkansokmen, you can also try:

```php
$searchResult = Book::multiMatchSearch()
    ->fields(['title^3', 'description^2'])
    ->query('My book')
    ->execute();
```

From the [official Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html#field-boost):

> Individual fields can be boosted with the caret (^) notation
