### ISSUE TITLE
Where clause in sorting

### ISSUE THREAD

**Issue by tcagkansokmen** [babenkoivan/elastic-scout-driver-plus#85]
I got data like;

```
products:
[
  {
    'title': first product,
      'categories: [
      {
        'name': blabla,
        'priority': 10
      },
      {
        'name': blabla2,
        'priority': 4
      }
  },
  {
    'title': new product,
      'categories: [
      {
        'name': blabla,
        'priority': 5
      },
      {
        'name': blabla2,
        'priority': 14
      }
  },
]
```

I need to make sorting where categories.name:blabla.

```
$searchResponse = Product::boolSearch()
    ->must('match', ['categories.name' => 'blabla'])
    ->sort('categories.priority')
    ->from(0)
    ->size(12)
    ->raw();
```

When I use code above, It sorts the results by every priority. But I want to take only sortings where categories.name: blabla

How can I use that query?

**Comment by babenkoivan** [comment]
Hey @tcagkansokmen, I think you need to implement [nested sorting](https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html#nested-sorting). You can use the `sortRaw` method:

```php
$searchResponse = Product::boolSearch()
    ->must('match', ['categories.name' => 'blabla'])
    ->sortRaw([ /* nested sorting */ ])
    ->from(0)
    ->size(12)
    ->raw();
```

I'm closing this one, cause it's a question regarding Elasticsearch usage itself and not the library.
