### ISSUE TITLE
MultiMatchQuery

### ISSUE THREAD

**Issue by Marian00P** [babenkoivan/elastic-scout-driver-plus#86]
Hi everyone, sorry for my English haha

does anyone know if is possible make a MultiMatchQuery and specify that the search value can be contained into a fields?

For example, something like this:

```
$queryBuilder = (new MultiMatchQueryBuilder())
                    ->fields([.....])
                    ->query('*'.$searchValue.'*')
```

I tried to use fuzzines, but I don't quite understand it.

I need replicate the behavior of `Document::search('*'.$searchValue.'*') ` but in multiple fields.

**Thanks** in advance

**Comment by babenkoivan** [comment]
Hi @Marian00P, I'm not sure if understood the problem. Why this doesn't work?

```php
$searchResult = Book::multiMatchSearch()
    ->fields($fields)
    ->query($searchValue)
    ->execute();
```

You don't really need to use it with wildcards unless you are trying to build a wildcard query:

```php
$searchResult = Book::wildcardSearch()
    ->field($field)
    ->value('*' . $searchValue . '*')
    ->execute();
```

**Comment by Marian00P** [comment]
But I need to find this searchValue in multiple fields, how can I apply wildCardSearch in multiple fields?

**Comment by Marian00P** [comment]
Mmhh, maybe this example clarifies the problem a bit.

Let's suppose we have the following user data:

```
[
    ...
    {first_name: Nikolas, last_name: Tesla, email: nik_tesla@gmail.com, phone_number: 123455(56)66, born: 1955},
    {first_name: Galileo, last_name: Galilei, email: g_galilei56@test.com, phone_number: 1234777888, born: 1960},
    {first_name: Eliseo, last_name: Terry, email: eliseo_terry@gmail.com, phone_number: 1234557888, born: 1957},
    {first_name: Isaac, last_name: Newton, email: i_newton@test.com, phone_number: 1234999(56)77, born: 1958},
    {first_name: Nicolas, last_name: Copernico, email: nic_coper@gmail.com, phone_number: 1234555766, born: 1959},
    ...
]
```
suppose we want to filter the users that were born between 1955 and 1959, and also we want the email, or the number to contain the number 56.

and keep in mind that `$fields = ['email', 'phone_number']` and `$searchValue = 56`


Well, in my code I go through each filter and create its respective queryBuilder and store it in an array `$queryBuilders` for later use in `User::boolSearch()->mustRaw($queryBuilders)->paginate(10)`

Basically,

```
...
$queryBuilderForBorns = (new RangeQueryBuilder())
                                    ->field('born')
                                    ->gte(1955)
                                    ->lte(1959);
array_push($queryBuilders, $queryBuilderForBorns)

// in the next line start the problem, I tried to solve this with

$queryBuilderForFindValue = (new MultiMatchQueryBuilder())
                                                      ->fields($fields)
                                                      ->query('*' . $searchValue . '*')
                                                      ->operator('or');                                   
```
... but it didn't work for me. :(

After getting your answer I tried to do the following, replacing the last part of the code with:

```
foreach ($fields as $field) {
      $queryBuilder1 = (new WildcardQueryBuilder())
                          ->field($field)
                          ->value('*' . $searchValue . '*');
      array_push($queryBuilders, $queryBuilder2->buildQuery());
}
```

But obviously it was not going to work, because when it finds one that does not match, all the previous result is overwritten.


**I hope my problem has been clarified, and sorry for the inconvenience. Thanks in advance.**

**Comment by Marian00P** [comment]
Ohh great, thank you very much!!!
