### ISSUE TITLE
search across multiple indices with query_string

### ISSUE THREAD

**Issue by Orest-Divintari** [babenkoivan/elastic-scout-driver-plus#87]
Is it possible to use `query_sring` within `bool` query like we use `match` or `term` ? 

For example, we can use 

```
Thread::boolSearch()->should('term', ['title' => 'search something']);
```

But I didn't find support for `query_string` to do

```
Thread::boolSearch()->should('query_string', 'search something');
```

Given that the following texts

`iPhone and iPad keyboard`
`iPhone keyboard`
`iPad keyboard`

I want to search across multiple indices the keywords `iPhone keyboard` and get all above texts as results.

For example

```
Thread::boolSearch()->join(Reply::class)->should('query_string', 'iPhone keyboard')->execute();
```

In order to achieve that right now I do the following

```
Thread::boolSearch()
    ->join(Reply::class)
    ->should(
          (new BoolQueryBuilder)
                    ->must('wildcard', ['title' => '*iphone*'])
                    ->must('wildcard', ['title' => '*keyboard*'])
     )->execute();
```

But then, the query can become quite long if want to search in fields `title` and `body`.

**Comment by emielmolenaar** [comment]
You can always use "shouldRaw" or "mustRaw", for example:

```
Query::bool()->shouldRaw([
    'query_string' => [
        'query' => $query,
    ],
]);
```
