### ISSUE TITLE
[CONSULT] How change default mapping

### ISSUE THREAD

**Issue by Marian00P** [babenkoivan/elastic-scout-driver-plus#88]
Hi, everyone

I need know how change de default mapping, some fields that I handle in database as string type but contains numbers, the default mapping set this field as long type and this breaks my inserts and throw BulkRequestException:

One more data, when value of this fields is only numeric (for example: 45454598989) all is okey, the insert did successfully. But, when the value contain a # (#45454598989), the insert is breaks.

I think that if change the mapping for this field to text type instead of long type this is resolved, but I dont know how make this.

Thanks in advance

**Comment by babenkoivan** [comment]
Hey @Marian00P, 

Have a look at this package https://github.com/babenkoivan/elastic-migrations. It allows you to create an index and configure the mapping. 

Closing this one as it's not a project-related question.
