### ISSUE TITLE
Range with term not working

### ISSUE THREAD

**Issue by tcagkansokmen** [babenkoivan/elastic-scout-driver-plus#89]
The code below not working, because It doesnt show most of the 'is_active' products.
When I remove is_active, It works well, and shows all products has is_active=1.

I couldnt understand why.
Why It shows some of products and not showing others.

     ```
 $products_ids = $product_ids
      ->must('range', ['quantity' => ['gte' => 1]])
      ->must('term', ['is_active' => 1])
      ->mustNot('term', ['type' => 'subscription']);
```

**Comment by babenkoivan** [comment]
Hey @tcagkansokmen, I think you need to check the index mapping. `is_active` must be boolean or integer.
