### ISSUE TITLE
Support for eager loading relations

### ISSUE THREAD

**Issue by oknoote** [babenkoivan/elastic-scout-driver-plus#9]
In order to reduce the number of subsequent MySQL requests after an ElasticSearch query.
Instead of iterating over the resultset and querying a related model on the fly, it would be nice to have the option to eager load relations in a similar fashion as Eloquent:
https://laravel.com/docs/7.x/eloquent-relationships#eager-loading

**Comment by babenkoivan** [comment]
Hey @oknoote, it's already possible. 

Let's say you search **books**, which have **author** relation:

```
$result = Book::rawSearch()
            ->query([
                'match' => [
                    'title' => $target->title,
                ],
            ])
            ->execute();
```

To load missing relations with a single query you can do the following:

```
$result->models()->loadMissing('author');
```

Even if you need to iterate over matches or models afterwards, no additional queries will be made.
