### ISSUE TITLE
Incorrect total records on pagination

### ISSUE THREAD

**Issue by Marian00P** [babenkoivan/elastic-scout-driver-plus#95]
Hi @babenkoivan , I need help with the next issue:

I have an entity with more than 2 million data, but when I do some search and apply some filters (let's suppose that the data that matchean are 1.5 million) when I make paginate(10) the total always comes set as maximum in 10.000.

Do you have any idea what the problem might be? Thank in advance.

**Comment by Marian00P** [comment]
@babenkoivan Attached is an image of the response from the back:
![image](https://user-images.githubusercontent.com/71725169/140538789-23aa0880-22d6-4a8b-9f5d-8caa7875dd8c.png)

The problem is the total value, correct value is 1.5millones.

**Comment by Marian00P** [comment]
I see that the solution is set **track_total_hits** with **true**, this worked for me in a booleanSearch QueryBuilder, but didn't work for me in Model::search('blabla')->where(blabla)->trackTotalHits(true);

**Comment by T3N4K4** [comment]
@Marian00P I haven't any knowledge of the package from @babenkoivan but this is a restriction of elasticsearch itself:

>By default, you cannot use from and size to page through more than 10,000 hits. This limit is a safeguard set by the index.max_result_window index setting. If you need to page through more than 10,000 hits, use the search_after parameter instead.
Source: https://www.elastic.co/guide/en/elasticsearch/reference/current/paginate-search-results.html

Maybe this PR addresses your issue then: https://github.com/babenkoivan/elastic-scout-driver-plus/pull/94

**Comment by babenkoivan** [comment]
Hey @Marian00P, as @T3N4K4 has already stated, a search over 10k hits is not supported at the moment.
