### ISSUE TITLE
Error Target class [ElasticScoutDriverPlus\Decorators\EngineDecorator] does not exist.

### ISSUE THREAD

**Issue by ankitaPurohit2021** [babenkoivan/elastic-scout-driver-plus#96]
@babenkoivan Can you update the Lumen documentation. I am getting  EngineDecorator class does not exists while following the Lumen installation steps. However I have noticed that this class has been removed in version 3.

Lumen documentation is working fine with version 2, but using version 3 need to change below code in the bootstrap/app.php for Lumen.

```
$app->extend(ElasticScoutDriver\Engine::class, function (Laravel\Scout\Engines\Engine $engine) use ($app) {
    return $app->make(ElasticScoutDriverPlus\Decorators\EngineDecorator::class, compact('engine'));
});
```

**Comment by 1x481n** [comment]
+1

**Comment by 1x481n** [comment]
I get it.
![image](https://user-images.githubusercontent.com/4003959/144004446-625c0dbb-abef-46a1-9ac2-90e0f8502ec6.png)

**Comment by babenkoivan** [comment]
The documentation is now updated 🙂
