### ISSUE TITLE
Documentation: what is the relationship between elastic-scout-driver-plus and elastic-scout-driver?

### ISSUE THREAD

**Issue by zhiyong80** [babenkoivan/elastic-scout-driver-plus#97]
Hi,

I have been using scout-elasticsearch-driver for a few years, then realized it has been abandoned. Composer suggested to use elastic-scout-drive as alternative. But there seems to be a plus version. Is the plus version a more feature rich one? I am a bit confused and cannot get a good idea which one to use after reading the readme  of both repo.

Can someone educate me on this? Thanks.

**Comment by babenkoivan** [comment]
Hi @zhiyong80.

We have two packages now:
1. [elastic-scout-driver](https://github.com/babenkoivan/elastic-scout-driver) is a trivial Scout driver for Elasticsearch, which strictly follows Scout interface and therefore guarantees that you can swap the driver without any (or minimal) code changes in your application.
2. [elastic-scout-driver-plus](https://github.com/babenkoivan/elastic-scout-driver-plus) provides many additional Elasticsearch-specific features such as aggregations, advanced search queries, etc. It is **not a standalone package** and it has to be installed after `elastic-scout-driver`.

If you need basic search functionality then you can go with `elastic-scout-driver`, if you need custom search queries or any other specific features that Elasticsearch provides, then you better also install `elastic-scout-driver-plus`.

**Comment by zhiyong80** [comment]
@babenkoivan this answers my question. Would you mind including this information in readme? That will help others get a better idea.

**Comment by babenkoivan** [comment]
@zhiyong80 it is mentioned [here](https://github.com/babenkoivan/elastic-scout-driver#advanced-search), but maybe it's not explicit enough 🙂
