### ISSUE TITLE
inner_hits highlights mising

### ISSUE THREAD

**Issue by Surt** [babenkoivan/elastic-scout-driver-plus#98]
First, great iteration over the library on version 3 @babenkoivan. I like it very much now. It's cleaner and works great!

I was playing with the new SearchResults object, which is better than the older, and I found (as suspected) that it does not return ```inner_hits```
I will try to find time to create the method ``` inner_hits``` at least on the ```Hit``` Decorator or the ```Search\Hit```. I can't promise anything but I will try to find the time.

**Comment by babenkoivan** [comment]
Hi @Surt, glad to hear you like it, and thank you for the PR! 

Until it's merged, you can access `inner_hits` as follows:

```php
$innerHits = $hit->raw()['inner_hits'];
```

**Comment by babenkoivan** [comment]
Hi @Surt, I've just released [v3.2.0](https://github.com/babenkoivan/elastic-scout-driver-plus/releases/tag/v3.2.0) with inner hits support 🎉
