### ISSUE TITLE
Empty result on ES 7.15.2 but works on ES 7.10.2

### ISSUE THREAD

**Issue by laTruffe79** [babenkoivan/elastic-scout-driver-plus#99]
| Software               | Version
| --------------------| ---------------
| PHP                          | 8.0.13
| Elasticsearch            | 7.15.2
| Laravel                     | 8.73.1
| Laravel Scout           | 8.6.1
| Elastic Scout Driver | 1.6.2

**Describe the bug**
Since I updated the stagging server ES has been updated to 7.15.2 and the same code working on my dev machine with ES 7.10.2 no longer works and return empty results . Off course I checked that the indexes are not empty ^_^
When I change the ELASTIC_HOST to my dev machine it works, the indexes are exactly the same.

**To Reproduce**

**Current behavior**

**Expected behavior**

**Comment by babenkoivan** [comment]
Hi @laTruffe79, I've run the tests against ES 7.15.2 and didn't notice any issues.
